package helpers;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;

public class AvlDEVHelper extends BaseHelper {

    public static void RegistracijaHelper() throws InterruptedException{

        String url = "https://avl.dev.smartweb.rs/consumer/";
        driver.navigate().to(url);
        driver.get("https://avl.dev.smartweb.rs/consumer/");
        WebElement Nalog = driver.findElement(By.xpath("/html/body/div[4]/header/div[2]/div[2]/div[1]/a"));
        Nalog.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[3]/div/div[2]/div/p/a")));
        WebElement NovN = driver.findElement(By.xpath("/html/body/div[4]/main/div[3]/div/div[2]/div/p/a"));
        NovN.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("firstname")));
        WebElement Ime = driver.findElement(By.name("firstname"));
        Ime.sendKeys("Nikola");
        WebElement Prezime = driver.findElement(By.name("lastname"));
        Prezime.sendKeys("Cebic");
        WebElement Mejl = driver.findElement(By.name("email"));
        Mejl.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Pass = driver.findElement(By.name("password"));
        Pass.sendKeys("Cebic123");
        WebElement Potvrda = driver.findElement(By.name("password_confirmation"));
        Potvrda.sendKeys("Cebic123");
        WebElement AJ = driver.findElement(By.xpath("/html/body/div[4]/main/div[3]/div/form/div/div[1]/button"));
        AJ.click();
    }

    public static void LoginHelper() throws InterruptedException{
        String url = "https://avl.dev.smartweb.rs/consumer/";
        driver.navigate().to(url);
        driver.get("https://avl.dev.smartweb.rs/consumer/");
        WebElement Nalog = driver.findElement(By.xpath("/html/body/div[4]/header/div[2]/div[2]/div[1]/a"));
        Nalog.click();
        WebElement Mejl = driver.findElement(By.name("login[username]"));
        Mejl.sendKeys("nikola.cebic@smartweb.rs");
        WebElement pass = driver.findElement(By.name("login[password]"));
        pass.sendKeys("Cebic123");
        WebElement Ajd = driver.findElement(By.id("send2"));
        Ajd.click();
    }

    public static void EbankingHelper() throws InterruptedException{
        String url = "https://avl.dev.smartweb.rs/consumer/";
        driver.navigate().to(url);
        driver.get("https://avl.dev.smartweb.rs/consumer/");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/header/div[2]/div[2]/div[4]/div/div[2]/nav/ul/li[2]/a/span[2]")));
        WebElement Sluske = driver.findElement(By.xpath("/html/body/div[4]/header/div[2]/div[2]/div[4]/div/div[2]/nav/ul/li[2]/a/span[2]"));
        Sluske.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[2]/div[2]/div[2]/a/span")));
        WebElement Bubice = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div[2]/div[2]/a/span"));
        Bubice.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[3]/div/div[1]/div[3]/div[2]/ol/li[4]/div/div[2]/strong/a")));
        WebElement JBL_sluske = driver.findElement(By.xpath("/html/body/div[4]/main/div[3]/div/div[1]/div[3]/div[2]/ol/li[4]/div/div[2]/strong/a"));
        JBL_sluske.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("option-label-color-92-item-728")));
        WebElement CrnaBoja = driver.findElement(By.id("option-label-color-92-item-728"));
        CrnaBoja.click();
        WebElement Buy = driver.findElement(By.id("product-addtocart-button"));
        Buy.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[1]/div[2]/div/div/div/a")));
        WebElement MiniKorpa = driver.findElement(By.xpath("/html/body/div[4]/main/div[1]/div[2]/div/div/div/a"));
        MiniKorpa.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[3]/div/div[2]/div[1]/ul/li/button/span")));
        WebElement nastavi = driver.findElement(By.xpath("/html/body/div[4]/main/div[3]/div/div[2]/div[1]/ul/li/button"));
        nastavi.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement Mejl = driver.findElement(By.id("customer-email"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Mejl));
        Mejl.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime = driver.findElement(By.name("firstname"));
        Ime.sendKeys("Nikola");
        WebElement Prezime = driver.findElement(By.name("lastname"));
        Prezime.sendKeys("Cebic");
        WebElement Ulica = driver.findElement(By.name("street[0]"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Ulica));
        Ulica.sendKeys("Blabla 23");
        WebElement Dgra = driver.findElement(By.name("city"));
        Dgra.sendKeys("Beograd");
        WebElement Postanski = driver.findElement(By.name("postcode"));
        Postanski.sendKeys("11090");
        WebElement Fon = driver.findElement(By.name("telephone"));
        Fon.sendKeys("065788455");
        Thread.sleep(5000);
        WebElement EBanking = driver.findElement(By.id("cashondelivery"));
        EBanking.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("billing-address-same-as-shipping")));
        WebElement MojaADR = driver.findElement(By.name("billing-address-same-as-shipping"));
        MojaADR.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[1]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input")));
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[1]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        Ime2.sendKeys("Nidza");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[1]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Ulica2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[1]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Ulica2.sendKeys("EEeehee 23");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[1]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[4]/div/input"));
        Grad2.sendKeys("Beograd");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[1]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[1]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[6]/div/input"));
        Fon2.sendKeys("0685455655");
        WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[1]/div[2]/div[2]/div/fieldset/div[3]/div/button[1]/span"));
        Azuriraj.click();
        Thread.sleep(5000);
        WebElement Kupi = driver.findElement(By.className("payment-methods"));
        Kupi.click();
    }

    public static void UplatnicaH() throws InterruptedException{
        String url = "https://avl.dev.smartweb.rs/consumer/";
        driver.navigate().to(url);
        driver.get("https://avl.dev.smartweb.rs/consumer/");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/header/div[2]/div[2]/div[4]/div/div[2]/nav/ul/li[2]/a/span[2]")));
        WebElement Sluske = driver.findElement(By.xpath("/html/body/div[4]/header/div[2]/div[2]/div[4]/div/div[2]/nav/ul/li[2]/a/span[2]"));
        Sluske.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[2]/div[2]/div[2]/a/span")));
        WebElement Bubice = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div[2]/div[2]/a/span"));
        Bubice.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[3]/div/div[1]/div[3]/div[2]/ol/li[4]/div/div[2]/strong/a")));
        WebElement JBL_sluske = driver.findElement(By.xpath("/html/body/div[4]/main/div[3]/div/div[1]/div[3]/div[2]/ol/li[4]/div/div[2]/strong/a"));
        JBL_sluske.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("option-label-color-92-item-728")));
        WebElement CrnaBoja = driver.findElement(By.id("option-label-color-92-item-728"));
        CrnaBoja.click();
        WebElement Buy = driver.findElement(By.id("product-addtocart-button"));
        Buy.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[1]/div[2]/div/div/div/a")));
        WebElement MiniKorpa = driver.findElement(By.xpath("/html/body/div[4]/main/div[1]/div[2]/div/div/div/a"));
        MiniKorpa.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[3]/div/div[2]/div[1]/ul/li/button/span")));
        WebElement nastavi = driver.findElement(By.xpath("/html/body/div[4]/main/div[3]/div/div[2]/div[1]/ul/li/button"));
        nastavi.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement Mejl = driver.findElement(By.id("customer-email"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Mejl));
        Mejl.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime = driver.findElement(By.name("firstname"));
        Ime.sendKeys("Nikola");
        WebElement Prezime = driver.findElement(By.name("lastname"));
        Prezime.sendKeys("Cebic");
        WebElement Ulica = driver.findElement(By.name("street[0]"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Ulica));
        Ulica.sendKeys("Blabla 23");
        WebElement Dgra = driver.findElement(By.name("city"));
        Dgra.sendKeys("Beograd");
        WebElement Postanski = driver.findElement(By.name("postcode"));
        Postanski.sendKeys("11090");
        WebElement Fon = driver.findElement(By.name("telephone"));
        Fon.sendKeys("065788455");
        Thread.sleep(5000);
        WebElement Uplatnica = driver.findElement(By.id("banktransfer"));
        Uplatnica.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("billing-address-same-as-shipping-banktransfer")));
        WebElement MojaADR = driver.findElement(By.id("billing-address-same-as-shipping-banktransfer"));
        MojaADR.click();
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[2]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Ime2));
        Ime2.sendKeys("Nidza");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[2]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Ulica2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[2]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Ulica2));
        Ulica2.sendKeys("EEeehee 23");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[2]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[4]/div/input"));
        Grad2.sendKeys("Beograd");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[2]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[2]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[6]/div/input"));
        Fon2.sendKeys("0685455655");
        WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[2]/div[2]/div[2]/div/fieldset/div[3]/div/button[1]"));
        Azuriraj.click();
        Thread.sleep(5000);
        WebElement Kupi = driver.findElement(By.className("payment-methods"));
        Kupi.click();
    }

    public static void VirmanHelper() throws InterruptedException{
        String url = "https://avl.dev.smartweb.rs/consumer/";
        driver.navigate().to(url);
        driver.get("https://avl.dev.smartweb.rs/consumer/");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/header/div[2]/div[2]/div[4]/div/div[2]/nav/ul/li[2]/a/span[2]")));
        WebElement Sluske = driver.findElement(By.xpath("/html/body/div[4]/header/div[2]/div[2]/div[4]/div/div[2]/nav/ul/li[2]/a/span[2]"));
        Sluske.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[2]/div[2]/div[2]/a/span")));
        WebElement Bubice = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div[2]/div[2]/a/span"));
        Bubice.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[3]/div/div[1]/div[3]/div[2]/ol/li[4]/div/div[2]/strong/a")));
        WebElement JBL_sluske = driver.findElement(By.xpath("/html/body/div[4]/main/div[3]/div/div[1]/div[3]/div[2]/ol/li[4]/div/div[2]/strong/a"));
        JBL_sluske.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("option-label-color-92-item-728")));
        WebElement CrnaBoja = driver.findElement(By.id("option-label-color-92-item-728"));
        CrnaBoja.click();
        WebElement Buy = driver.findElement(By.id("product-addtocart-button"));
        Buy.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[1]/div[2]/div/div/div/a")));
        WebElement MiniKorpa = driver.findElement(By.xpath("/html/body/div[4]/main/div[1]/div[2]/div/div/div/a"));
        MiniKorpa.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[3]/div/div[2]/div[1]/ul/li/button/span")));
        WebElement nastavi = driver.findElement(By.xpath("/html/body/div[4]/main/div[3]/div/div[2]/div[1]/ul/li/button"));
        nastavi.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement Mejl = driver.findElement(By.id("customer-email"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Mejl));
        Mejl.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime = driver.findElement(By.name("firstname"));
        Ime.sendKeys("Nikola");
        WebElement Prezime = driver.findElement(By.name("lastname"));
        Prezime.sendKeys("Cebic");
        WebElement Ulica = driver.findElement(By.name("street[0]"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Ulica));
        Ulica.sendKeys("Blabla 23");
        WebElement Dgra = driver.findElement(By.name("city"));
        Dgra.sendKeys("Beograd");
        WebElement Postanski = driver.findElement(By.name("postcode"));
        Postanski.sendKeys("11090");
        WebElement Fon = driver.findElement(By.name("telephone"));
        Fon.sendKeys("065788455");
        Thread.sleep(5000);
        WebElement VIRMAN = driver.findElement(By.id("simple"));
        VIRMAN.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("billing-address-same-as-shipping-simple")));
        WebElement MojaADR = driver.findElement(By.id("billing-address-same-as-shipping-simple"));
        MojaADR.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[3]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input")));
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[3]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        Ime2.sendKeys("Nidza");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[3]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Ulica2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[3]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Ulica2.sendKeys("Trte Mrte 33");
        WebElement Dgra2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[3]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[4]/div/input"));
        Dgra2.sendKeys("Beograd");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[3]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[3]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[6]/div/input"));
        Fon2.sendKeys("068754555");
        WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[3]/div[2]/div[2]/div/fieldset/div[3]/div/button[1]/span"));
        Azuriraj.click();
        Thread.sleep(5000);
        WebElement Kupi = driver.findElement(By.className("payment-methods"));
        Kupi.click();

    }

    public static void PouzeceHelper() throws InterruptedException{
        String url = "https://avl.dev.smartweb.rs/consumer/";
        driver.navigate().to(url);
        driver.get("https://avl.dev.smartweb.rs/consumer/");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/header/div[2]/div[2]/div[4]/div/div[2]/nav/ul/li[2]/a/span[2]")));
        WebElement Sluske = driver.findElement(By.xpath("/html/body/div[4]/header/div[2]/div[2]/div[4]/div/div[2]/nav/ul/li[2]/a/span[2]"));
        Sluske.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[2]/div[2]/div[2]/a/span")));
        WebElement Bubice = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div[2]/div[2]/a/span"));
        Bubice.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[3]/div/div[1]/div[3]/div[2]/ol/li[4]/div/div[2]/strong/a")));
        WebElement JBL_sluske = driver.findElement(By.xpath("/html/body/div[4]/main/div[3]/div/div[1]/div[3]/div[2]/ol/li[4]/div/div[2]/strong/a"));
        JBL_sluske.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("option-label-color-92-item-728")));
        WebElement CrnaBoja = driver.findElement(By.id("option-label-color-92-item-728"));
        CrnaBoja.click();
        WebElement Buy = driver.findElement(By.id("product-addtocart-button"));
        Buy.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[1]/div[2]/div/div/div/a")));
        WebElement MiniKorpa = driver.findElement(By.xpath("/html/body/div[4]/main/div[1]/div[2]/div/div/div/a"));
        MiniKorpa.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[3]/div/div[2]/div[1]/ul/li/button/span")));
        WebElement nastavi = driver.findElement(By.xpath("/html/body/div[4]/main/div[3]/div/div[2]/div[1]/ul/li/button"));
        nastavi.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement Mejl = driver.findElement(By.id("customer-email"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Mejl));
        Mejl.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime = driver.findElement(By.name("firstname"));
        Ime.sendKeys("Nikola");
        WebElement Prezime = driver.findElement(By.name("lastname"));
        Prezime.sendKeys("Cebic");
        WebElement Ulica = driver.findElement(By.name("street[0]"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Ulica));
        Ulica.sendKeys("Blabla 23");
        WebElement Dgra = driver.findElement(By.name("city"));
        Dgra.sendKeys("Beograd");
        WebElement Postanski = driver.findElement(By.name("postcode"));
        Postanski.sendKeys("11090");
        WebElement Fon = driver.findElement(By.name("telephone"));
        Fon.sendKeys("065788455");
        Thread.sleep(5000);
        WebElement POUZECE = driver.findElement(By.id("checkmo"));
        POUZECE.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("billing-address-same-as-shipping-checkmo")));
        WebElement MojaADR = driver.findElement(By.id("billing-address-same-as-shipping-checkmo"));
        MojaADR.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[4]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input")));
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[4]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        Ime2.sendKeys("Nidza");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[4]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Ulica2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[4]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Ulica2.sendKeys("Trte Mrte 23");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[4]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[4]/div/input"));
        Grad2.sendKeys("Thehehe 23");
        WebElement Postanksi2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[4]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
        Postanksi2.sendKeys("11090");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[4]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[6]/div/input"));
        Fon2.sendKeys("06874856552");
        WebElement Azuiriraj = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[4]/div[2]/div[2]/div/fieldset/div[3]/div/button[1]/span"));
        Azuiriraj.click();
        Thread.sleep(5000);
        WebElement Kupi = driver.findElement(By.className("payment-methods"));
        Kupi.click();
    }

    public static void PlatnaHelper() throws InterruptedException{
        String url = "https://avl.dev.smartweb.rs/consumer/";
        driver.navigate().to(url);
        driver.get("https://avl.dev.smartweb.rs/consumer/");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/header/div[2]/div[2]/div[4]/div/div[2]/nav/ul/li[2]/a/span[2]")));
        WebElement Sluske = driver.findElement(By.xpath("/html/body/div[4]/header/div[2]/div[2]/div[4]/div/div[2]/nav/ul/li[2]/a/span[2]"));
        Sluske.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[2]/div[2]/div[2]/a/span")));
        WebElement Bubice = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div[2]/div[2]/a/span"));
        Bubice.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[3]/div/div[1]/div[3]/div[2]/ol/li[4]/div/div[2]/strong/a")));
        WebElement JBL_sluske = driver.findElement(By.xpath("/html/body/div[4]/main/div[3]/div/div[1]/div[3]/div[2]/ol/li[4]/div/div[2]/strong/a"));
        JBL_sluske.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("option-label-color-92-item-728")));
        WebElement CrnaBoja = driver.findElement(By.id("option-label-color-92-item-728"));
        CrnaBoja.click();
        WebElement Buy = driver.findElement(By.id("product-addtocart-button"));
        Buy.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[1]/div[2]/div/div/div/a")));
        WebElement MiniKorpa = driver.findElement(By.xpath("/html/body/div[4]/main/div[1]/div[2]/div/div/div/a"));
        MiniKorpa.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[4]/main/div[3]/div/div[2]/div[1]/ul/li/button/span")));
        WebElement nastavi = driver.findElement(By.xpath("/html/body/div[4]/main/div[3]/div/div[2]/div[1]/ul/li/button"));
        nastavi.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement Mejl = driver.findElement(By.id("customer-email"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Mejl));
        Mejl.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime = driver.findElement(By.name("firstname"));
        Ime.sendKeys("Nikola");
        WebElement Prezime = driver.findElement(By.name("lastname"));
        Prezime.sendKeys("Cebic");
        WebElement Ulica = driver.findElement(By.name("street[0]"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Ulica));
        Ulica.sendKeys("Blabla 23");
        WebElement Dgra = driver.findElement(By.name("city"));
        Dgra.sendKeys("Beograd");
        WebElement Postanski = driver.findElement(By.name("postcode"));
        Postanski.sendKeys("11090");
        WebElement Fon = driver.findElement(By.name("telephone"));
        Fon.sendKeys("065788455");
        Thread.sleep(5000);
        WebElement PLATNAK = driver.findElement(By.id("raiffeisen"));
        PLATNAK.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("billing-address-same-as-shipping-raiffeisen")));
        WebElement MojaADR = driver.findElement(By.id("billing-address-same-as-shipping-raiffeisen"));
        MojaADR.click();
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[5]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        Ime2.sendKeys("Nidza");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[5]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Ulica2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[5]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Ulica2.sendKeys("Uraaa uraa 2");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[5]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[4]/div/input"));
        Grad2.sendKeys("Beograd");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[5]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[4]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[5]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[6]/div/input"));
        Fon2.sendKeys("065412666");
        WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[5]/main/div[2]/div/div[2]/div[5]/div[2]/div[1]/div[2]/li/div/form/fieldset/div[1]/div/div/div[2]/div/div[5]/div[2]/div[2]/div/fieldset/div[3]/div/button[1]/span"));
        Azuriraj.click();
        Thread.sleep(5000);
        WebElement Kupi = driver.findElement(By.className("payment-methods"));
        Kupi.click();
    }

    public static void SearchH() throws InterruptedException{
        String url = "https://avl.dev.smartweb.rs/consumer/";
        driver.navigate().to(url);
        driver.get("https://avl.dev.smartweb.rs/consumer/");
        WebElement Lupa = driver.findElement(By.xpath("/html/body/div[4]/header/div[2]/div[2]/div[5]/div[1]"));
        Lupa.click();
        WebElement Kucaj = driver.findElement(By.name("q"));
        Kucaj.sendKeys("Slusalice");
        Kucaj.sendKeys(Keys.ENTER);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("amasty-shopby-product-list")));
        WebElement Result = driver.findElement(By.id("amasty-shopby-product-list"));
        System.out.println(Result.getText());
    }
}
