package helpers;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;

public class BeoCarHelper extends BaseHelper {

 private static void Registracija(String Ime, String Prezime, String Email, String Lozinka, String PotvrdaLozinke) throws InterruptedException {
  String url = "https://beocar.dev.smartweb.rs/";
  driver.navigate().to(url);
  driver.get("https://beocar.dev.smartweb.rs/");
  WebElement Registracijadugme = driver.findElement(By.id("idI2NpSCjI"));
  Registracijadugme.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("firstname")));
  WebElement ImeField = driver.findElement(By.id("firstname"));
  ImeField.sendKeys(Ime);
  WebElement PrezimeField = driver.findElement(By.id("lastname"));
  PrezimeField.sendKeys(Prezime);

  WebElement EmailField = driver.findElement(By.xpath("/html/body/div[5]/div[2]/div/div[2]/div[2]/div[1]/form/fieldset[2]/div[1]/div/input"));
  EmailField.sendKeys(Email);
  WebElement LozinkaField = driver.findElement(By.id("password"));
  LozinkaField.sendKeys(Lozinka);
  WebElement PotvrdaLozinkeField = driver.findElement(By.id("password-confirmation"));
  PotvrdaLozinkeField.sendKeys(PotvrdaLozinke);
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/div[2]/div/div[2]/div[2]/div[1]/form/div/div[1]/button/span")));
  WebElement RegButton = driver.findElement(By.xpath("/html/body/div[5]/div[2]/div/div[2]/div[2]/div[1]/form/div/div[1]/button/span"));
  wdWait.until(ExpectedConditions.elementToBeClickable(RegButton));
  RegButton.click();
  Thread.sleep(3000);

 }

 public static void DefRegistracija() throws InterruptedException {
  Registracija("Nikola", "Cebic", "nikola.cebic@smartweb.rs", "Cebic123", "Cebic123");
 }

 public static void DefLogin() throws InterruptedException {
  String url = "https://beocar.dev.smartweb.rs/";
  driver.navigate().to(url);
  driver.get("https://beocar.dev.smartweb.rs/");
  WebElement PrijaviSe = driver.findElement(By.xpath("/html/body/div[5]/header/div/div/div[2]/div/ul/li[1]/a[1]"));
  PrijaviSe.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("login[username]")));
  WebElement EmailPolje = driver.findElement(By.name("login[username]"));
  EmailPolje.sendKeys("nikola.cebic@smartweb.rs");
  WebElement Pass = driver.findElement(By.name("login[password]"));
  Pass.sendKeys("Cebic123");
  WebElement LoginButton = driver.findElement(By.id("send2"));
  LoginButton.click();
  Thread.sleep(3000);

 }

 public static void RacuniProdavnica1() throws InterruptedException {
  DefLogin();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img")));
  WebElement Spring = driver.findElement(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img"));
  Spring.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("product-addtocart-button")));
  WebElement DodajUKorpu = driver.findElement(By.id("product-addtocart-button"));
  DodajUKorpu.click();
  Thread.sleep(4000);
  WebElement MiniKorpa = driver.findElement(By.className("minicart-wrapper"));
  wdWait.until(ExpectedConditions.elementToBeClickable(MiniKorpa));
  MiniKorpa.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
  WebElement NastaviDalje = driver.findElement(By.id("top-cart-btn-checkout"));
  NastaviDalje.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("street[0]")));
  WebElement Ulica1 = driver.findElement(By.name("street[0]"));
  Ulica1.sendKeys("BlaBla 4");
  WebElement Grad1 = driver.findElement(By.name("city"));
  Grad1.sendKeys("Beograd");
  WebElement Postanski1 = driver.findElement(By.name("postcode"));
  Postanski1.sendKeys("11090");
  WebElement Fontele = driver.findElement(By.name("telephone"));
  Fontele.sendKeys("062227362");

  JavascriptExecutor jse = (JavascriptExecutor) driver;
  jse.executeScript("window.scrollBy(0,250)");
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("banktransfer")));
  WebElement PrekoRacuna = driver.findElement(By.id("banktransfer"));
  wdWait.until(ExpectedConditions.elementToBeClickable(PrekoRacuna));
  PrekoRacuna.click();
  Thread.sleep(5000);
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("billing-address-same-as-shipping")));
  WebElement MojaAdresaista = driver.findElement(By.name("billing-address-same-as-shipping"));
  MojaAdresaista.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input")));
  WebElement NovaAdresa = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
  NovaAdresa.sendKeys("Boljevci 2");
  WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
  Grad2.sendKeys("Negotin");
  WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[8]/div/input"));
  Postanski2.sendKeys("11440");
  WebElement Fon = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
  Fon.sendKeys("062227362");
  WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[3]/div/button[1]/span"));
  Azuriraj.click();
  Thread.sleep(8000);
  WebElement LicnoPreuzimanje1 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[2]/li/div/div/div/div[2]/form/div[1]/table/tbody/tr[1]/td[1]/input"));
  LicnoPreuzimanje1.click();
  WebElement UsloviK = driver.findElement(By.id("agreement__1"));
  UsloviK.click();
  WebElement Kupi = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[3]/div[4]/div/div/button"));
  Kupi.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("maincontent")));
  WebElement Result = driver.findElement(By.id("maincontent"));
  System.out.println(Result.getText());


  Thread.sleep(4000);
 }

 public static void RacuniProdavnica2() throws InterruptedException{
  DefLogin();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img")));
  WebElement Spring = driver.findElement(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img"));
  Spring.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("product-addtocart-button")));
  WebElement DodajUKorpu = driver.findElement(By.id("product-addtocart-button"));
  DodajUKorpu.click();
  Thread.sleep(4000);
  WebElement MiniKorpa = driver.findElement(By.className("minicart-wrapper"));
  wdWait.until(ExpectedConditions.elementToBeClickable(MiniKorpa));
  MiniKorpa.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
  WebElement NastaviDalje = driver.findElement(By.id("top-cart-btn-checkout"));
  NastaviDalje.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("street[0]")));
  WebElement Ulica1 = driver.findElement(By.name("street[0]"));
  Ulica1.sendKeys("BlaBla 4");
  WebElement Grad1 = driver.findElement(By.name("city"));
  Grad1.sendKeys("Beograd");
  WebElement Postanski1 = driver.findElement(By.name("postcode"));
  Postanski1.sendKeys("11090");
  WebElement Fontele = driver.findElement(By.name("telephone"));
  Fontele.sendKeys("062227362");

  JavascriptExecutor jse = (JavascriptExecutor) driver;
  jse.executeScript("window.scrollBy(0,250)");
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("banktransfer")));
  WebElement PrekoRacuna = driver.findElement(By.id("banktransfer"));
  wdWait.until(ExpectedConditions.elementToBeClickable(PrekoRacuna));
  PrekoRacuna.click();
  Thread.sleep(5000);
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("billing-address-same-as-shipping-shared")));
  WebElement MojaAdresaista = driver.findElement(By.id("billing-address-same-as-shipping-shared"));
  wdWait.until(ExpectedConditions.elementToBeClickable(MojaAdresaista));
  MojaAdresaista.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input")));
  WebElement NovaAdresa = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
  NovaAdresa.sendKeys("Boljevci 2");
  WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
  Grad2.sendKeys("Negotin");
  WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[8]/div/input"));
  Postanski2.sendKeys("11440");
  WebElement Fon = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
  Fon.sendKeys("062227362");
  WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[3]/div/button[1]/span"));
  Azuriraj.click();
  Thread.sleep(5000);
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[2]/li/div/div/div/div[2]/form/div[1]/table/tbody/tr[2]/td[1]/input")));
  WebElement Prodavnica2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[2]/li/div/div/div/div[2]/form/div[1]/table/tbody/tr[2]/td[1]/input"));
  Prodavnica2.click();
  Thread.sleep(5000);
  WebElement UsloviK = driver.findElement(By.id("agreement__1"));
  UsloviK.click();
  WebElement Kupi = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[3]/div[4]/div/div/button"));
  Kupi.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("maincontent")));
  WebElement Result = driver.findElement(By.id("maincontent"));
  System.out.println(Result.getText());
 }

 public static void RacuniProdavnica3() throws InterruptedException{
  DefLogin();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img")));
  WebElement Spring = driver.findElement(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img"));
  Spring.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("product-addtocart-button")));
  WebElement DodajUKorpu = driver.findElement(By.id("product-addtocart-button"));
  DodajUKorpu.click();
  Thread.sleep(4000);
  WebElement MiniKorpa = driver.findElement(By.className("minicart-wrapper"));
  wdWait.until(ExpectedConditions.elementToBeClickable(MiniKorpa));
  MiniKorpa.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
  WebElement NastaviDalje = driver.findElement(By.id("top-cart-btn-checkout"));
  NastaviDalje.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("street[0]")));
  WebElement Ulica1 = driver.findElement(By.name("street[0]"));
  Ulica1.sendKeys("BlaBla 4");
  WebElement Grad1 = driver.findElement(By.name("city"));
  Grad1.sendKeys("Beograd");
  WebElement Postanski1 = driver.findElement(By.name("postcode"));
  Postanski1.sendKeys("11090");
  WebElement Fontele = driver.findElement(By.name("telephone"));
  Fontele.sendKeys("062227362");

  JavascriptExecutor jse = (JavascriptExecutor) driver;
  jse.executeScript("window.scrollBy(0,250)");
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("banktransfer")));
  WebElement PrekoRacuna = driver.findElement(By.id("banktransfer"));
  wdWait.until(ExpectedConditions.elementToBeClickable(PrekoRacuna));
  PrekoRacuna.click();
  Thread.sleep(5000);
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("billing-address-same-as-shipping-shared")));
  WebElement MojaAdresaista = driver.findElement(By.id("billing-address-same-as-shipping-shared"));
  wdWait.until(ExpectedConditions.elementToBeClickable(MojaAdresaista));
  MojaAdresaista.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input")));
  WebElement NovaAdresa = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
  NovaAdresa.sendKeys("Boljevci 2");
  WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
  Grad2.sendKeys("Negotin");
  WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[8]/div/input"));
  Postanski2.sendKeys("11440");
  WebElement Fon = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
  Fon.sendKeys("062227362");
  WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[3]/div/button[1]/span"));
  Azuriraj.click();
  Thread.sleep(5000);
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[2]/li/div/div/div/div[2]/form/div[1]/table/tbody/tr[3]/td[1]/input")));
  WebElement Prodavnica3 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[2]/li/div/div/div/div[2]/form/div[1]/table/tbody/tr[3]/td[1]/input"));
  Prodavnica3.click();
  Thread.sleep(5000);
  WebElement UsloviK = driver.findElement(By.id("agreement__1"));
  UsloviK.click();
  WebElement Kupi = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[3]/div[4]/div/div/button"));
  Kupi.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("maincontent")));
  WebElement Result = driver.findElement(By.id("maincontent"));
  System.out.println(Result.getText());
 }

 public static void Racunikurir() throws InterruptedException{
  DefLogin();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img")));
  WebElement Spring = driver.findElement(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img"));
  Spring.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("product-addtocart-button")));
  WebElement DodajUKorpu = driver.findElement(By.id("product-addtocart-button"));
  DodajUKorpu.click();
  Thread.sleep(4000);
  WebElement MiniKorpa = driver.findElement(By.className("minicart-wrapper"));
  wdWait.until(ExpectedConditions.elementToBeClickable(MiniKorpa));
  MiniKorpa.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
  WebElement NastaviDalje = driver.findElement(By.id("top-cart-btn-checkout"));
  NastaviDalje.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("street[0]")));
  WebElement Ulica1 = driver.findElement(By.name("street[0]"));
  Ulica1.sendKeys("BlaBla 4");
  WebElement Grad1 = driver.findElement(By.name("city"));
  Grad1.sendKeys("Beograd");
  WebElement Postanski1 = driver.findElement(By.name("postcode"));
  Postanski1.sendKeys("11090");
  WebElement Fontele = driver.findElement(By.name("telephone"));
  Fontele.sendKeys("062227362");

  JavascriptExecutor jse = (JavascriptExecutor) driver;
  jse.executeScript("window.scrollBy(0,250)");
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("banktransfer")));
  WebElement PrekoRacuna = driver.findElement(By.id("banktransfer"));
  wdWait.until(ExpectedConditions.elementToBeClickable(PrekoRacuna));
  PrekoRacuna.click();
  Thread.sleep(5000);
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("billing-address-same-as-shipping-shared")));
  WebElement MojaAdresaista = driver.findElement(By.id("billing-address-same-as-shipping-shared"));
  wdWait.until(ExpectedConditions.elementToBeClickable(MojaAdresaista));
  MojaAdresaista.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input")));
  WebElement NovaAdresa = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
  NovaAdresa.sendKeys("Boljevci 2");
  WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
  Grad2.sendKeys("Negotin");
  WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[8]/div/input"));
  Postanski2.sendKeys("11440");
  WebElement Fon = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
  Fon.sendKeys("062227362");
  WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[3]/div/button[1]/span"));
  Azuriraj.click();
  Thread.sleep(5000);
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[2]/li/div/div/div/div[2]/form/div[1]/table/tbody/tr[4]/td[1]/input")));
  WebElement Kurir = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[2]/li/div/div/div/div[2]/form/div[1]/table/tbody/tr[4]/td[1]/input"));
  Kurir.click();
  Thread.sleep(5000);
  WebElement UsloviK = driver.findElement(By.id("agreement__1"));
  UsloviK.click();
  WebElement Kupi = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[3]/div[4]/div/div/button"));
  Kupi.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("maincontent")));
  WebElement Result = driver.findElement(By.id("maincontent"));
  System.out.println(Result.getText());
 }

 public static void GotovinaIProdza1() throws InterruptedException {
  DefLogin();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img")));
  WebElement Spring = driver.findElement(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img"));
  Spring.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("product-addtocart-button")));
  WebElement DodajUKorpu = driver.findElement(By.id("product-addtocart-button"));
  DodajUKorpu.click();
  Thread.sleep(4000);
  WebElement MiniKorpa = driver.findElement(By.className("minicart-wrapper"));
  wdWait.until(ExpectedConditions.elementToBeClickable(MiniKorpa));
  MiniKorpa.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
  WebElement NastaviDalje = driver.findElement(By.id("top-cart-btn-checkout"));
  NastaviDalje.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("street[0]")));
  WebElement Ulica1 = driver.findElement(By.name("street[0]"));
  Ulica1.sendKeys("BlaBla 4");
  WebElement Grad1 = driver.findElement(By.name("city"));
  Grad1.sendKeys("Beograd");
  WebElement Postanski1 = driver.findElement(By.name("postcode"));
  Postanski1.sendKeys("11090");
  WebElement Fontele = driver.findElement(By.name("telephone"));
  Fontele.sendKeys("062227362");
  Thread.sleep(8000);
  JavascriptExecutor jse = (JavascriptExecutor) driver;
  jse.executeScript("window.scrollBy(0,250)");
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("cashondelivery")));
  WebElement GotovinaPlacanje = driver.findElement(By.id("cashondelivery"));
  wdWait.until(ExpectedConditions.elementToBeClickable(GotovinaPlacanje));
  GotovinaPlacanje.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("billing-address-same-as-shipping")));
  WebElement MojaAdresaista = driver.findElement(By.name("billing-address-same-as-shipping"));
  MojaAdresaista.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input")));
  WebElement NovaAdresa = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
  NovaAdresa.sendKeys("Boljevci 2");
  WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
  Grad2.sendKeys("Negotin");
  WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[8]/div/input"));
  Postanski2.sendKeys("11440");
  WebElement Fon = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
  Fon.sendKeys("062227362");
  WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[3]/div/button[1]/span"));
  Azuriraj.click();
  WebElement LicnoPreuzimanje1 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[2]/li/div/div/div/div[2]/form/div[1]/table/tbody/tr[1]/td[1]/input"));
  LicnoPreuzimanje1.click();
  WebElement UsloviK = driver.findElement(By.id("agreement__1"));
  UsloviK.click();
  WebElement Kupi = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[3]/div[4]/div/div/button"));
  Kupi.click();
  Thread.sleep(4000);

 }

 public static void GotovinaIProdza2() throws InterruptedException{
  DefLogin();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img")));
  WebElement Spring = driver.findElement(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img"));
  Spring.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("product-addtocart-button")));
  WebElement DodajUKorpu = driver.findElement(By.id("product-addtocart-button"));
  DodajUKorpu.click();
  Thread.sleep(4000);
  WebElement MiniKorpa = driver.findElement(By.className("minicart-wrapper"));
  wdWait.until(ExpectedConditions.elementToBeClickable(MiniKorpa));
  MiniKorpa.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
  WebElement NastaviDalje = driver.findElement(By.id("top-cart-btn-checkout"));
  NastaviDalje.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("street[0]")));
  WebElement Ulica1 = driver.findElement(By.name("street[0]"));
  Ulica1.sendKeys("BlaBla 4");
  WebElement Grad1 = driver.findElement(By.name("city"));
  Grad1.sendKeys("Beograd");
  WebElement Postanski1 = driver.findElement(By.name("postcode"));
  Postanski1.sendKeys("11090");
  WebElement Fontele = driver.findElement(By.name("telephone"));
  Fontele.sendKeys("062227362");
  Thread.sleep(8000);
  JavascriptExecutor jse = (JavascriptExecutor) driver;
  jse.executeScript("window.scrollBy(0,250)");
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("cashondelivery")));
  WebElement GotovinaPlacanje = driver.findElement(By.id("cashondelivery"));
  wdWait.until(ExpectedConditions.elementToBeClickable(GotovinaPlacanje));
  GotovinaPlacanje.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("billing-address-same-as-shipping")));
  WebElement MojaAdresaista = driver.findElement(By.name("billing-address-same-as-shipping"));
  MojaAdresaista.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input")));
  WebElement NovaAdresa = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
  NovaAdresa.sendKeys("Boljevci 2");
  WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
  Grad2.sendKeys("Negotin");
  WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[8]/div/input"));
  Postanski2.sendKeys("11440");
  WebElement Fon = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
  Fon.sendKeys("062227362");
  WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[3]/div/button[1]/span"));
  Azuriraj.click();
  WebElement LicnoPreuzimanje2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[2]/li/div/div/div/div[2]/form/div[1]/table/tbody/tr[2]/td[1]/input"));
  LicnoPreuzimanje2.click();
  WebElement UsloviK = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[2]/li/div/div/div/div[2]/form/div[1]/table/tbody/tr[2]/td[1]/input"));
  UsloviK.click();
  WebElement Kupi = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[3]/div[4]/div/div/button"));
  Kupi.click();
  Thread.sleep(4000);
 }

 public static  void GotovinaIProdza3() throws InterruptedException{
  DefLogin();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img")));
  WebElement Spring = driver.findElement(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img"));
  Spring.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("product-addtocart-button")));
  WebElement DodajUKorpu = driver.findElement(By.id("product-addtocart-button"));
  DodajUKorpu.click();
  Thread.sleep(4000);
  WebElement MiniKorpa = driver.findElement(By.className("minicart-wrapper"));
  wdWait.until(ExpectedConditions.elementToBeClickable(MiniKorpa));
  MiniKorpa.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
  WebElement NastaviDalje = driver.findElement(By.id("top-cart-btn-checkout"));
  NastaviDalje.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("street[0]")));
  WebElement Ulica1 = driver.findElement(By.name("street[0]"));
  Ulica1.sendKeys("BlaBla 4");
  WebElement Grad1 = driver.findElement(By.name("city"));
  Grad1.sendKeys("Beograd");
  WebElement Postanski1 = driver.findElement(By.name("postcode"));
  Postanski1.sendKeys("11090");
  WebElement Fontele = driver.findElement(By.name("telephone"));
  Fontele.sendKeys("062227362");
  Thread.sleep(8000);
  JavascriptExecutor jse = (JavascriptExecutor) driver;
  jse.executeScript("window.scrollBy(0,250)");
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("cashondelivery")));
  WebElement GotovinaPlacanje = driver.findElement(By.id("cashondelivery"));
  wdWait.until(ExpectedConditions.elementToBeClickable(GotovinaPlacanje));
  GotovinaPlacanje.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("billing-address-same-as-shipping")));
  WebElement MojaAdresaista = driver.findElement(By.name("billing-address-same-as-shipping"));
  MojaAdresaista.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input")));
  WebElement NovaAdresa = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
  NovaAdresa.sendKeys("Boljevci 2");
  WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
  Grad2.sendKeys("Negotin");
  WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[8]/div/input"));
  Postanski2.sendKeys("11440");
  WebElement Fon = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
  Fon.sendKeys("062227362");
  WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[3]/div/button[1]/span"));
  Azuriraj.click();
  WebElement LicnoPreuzimanje3 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[2]/li/div/div/div/div[2]/form/div[1]/table/tbody/tr[3]/td[1]/input"));
  LicnoPreuzimanje3.click();
  WebElement UsloviK = driver.findElement(By.id("agreement__1"));
  UsloviK.click();
  WebElement Kupi = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[3]/div[4]/div/div/button"));
  Kupi.click();
  Thread.sleep(4000);
 }

 public static void GotovinaIKurir() throws InterruptedException{
  DefLogin();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img")));
  WebElement Spring = driver.findElement(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img"));
  Spring.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("product-addtocart-button")));
  WebElement DodajUKorpu = driver.findElement(By.id("product-addtocart-button"));
  DodajUKorpu.click();
  Thread.sleep(4000);
  WebElement MiniKorpa = driver.findElement(By.className("minicart-wrapper"));
  wdWait.until(ExpectedConditions.elementToBeClickable(MiniKorpa));
  MiniKorpa.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
  WebElement NastaviDalje = driver.findElement(By.id("top-cart-btn-checkout"));
  NastaviDalje.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("street[0]")));
  WebElement Ulica1 = driver.findElement(By.name("street[0]"));
  Ulica1.sendKeys("BlaBla 4");
  WebElement Grad1 = driver.findElement(By.name("city"));
  Grad1.sendKeys("Beograd");
  WebElement Postanski1 = driver.findElement(By.name("postcode"));
  Postanski1.sendKeys("11090");
  WebElement Fontele = driver.findElement(By.name("telephone"));
  Fontele.sendKeys("062227362");
  Thread.sleep(8000);
  JavascriptExecutor jse = (JavascriptExecutor) driver;
  jse.executeScript("window.scrollBy(0,250)");
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("cashondelivery")));
  WebElement GotovinaPlacanje = driver.findElement(By.id("cashondelivery"));
  wdWait.until(ExpectedConditions.elementToBeClickable(GotovinaPlacanje));
  GotovinaPlacanje.click();
  Thread.sleep(8000);
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("billing-address-same-as-shipping")));
  WebElement MojaAdresaista = driver.findElement(By.name("billing-address-same-as-shipping"));
  MojaAdresaista.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input")));
  WebElement NovaAdresa = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
  NovaAdresa.sendKeys("Boljevci 2");
  WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
  Grad2.sendKeys("Negotin");
  WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[8]/div/input"));
  Postanski2.sendKeys("11440");
  WebElement Fon = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
  Fon.sendKeys("062227362");
  WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[3]/div/button[1]/span"));
  Azuriraj.click();
  WebElement Kurir = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[2]/li/div/div/div/div[2]/form/div[1]/table/tbody/tr[4]/td[1]/input"));
  Kurir.click();
  WebElement UsloviK = driver.findElement(By.id("agreement__1"));
  UsloviK.click();
  WebElement Kupi = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[3]/div[4]/div/div/button"));
  Kupi.click();
 }


 public static void KarticaIProdza1() throws InterruptedException {
  DefLogin();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img")));
  WebElement Spring = driver.findElement(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img"));
  Spring.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("product-addtocart-button")));
  WebElement DodajUKorpu = driver.findElement(By.id("product-addtocart-button"));
  DodajUKorpu.click();
  Thread.sleep(4000);
  WebElement MiniKorpa = driver.findElement(By.className("minicart-wrapper"));
  wdWait.until(ExpectedConditions.elementToBeClickable(MiniKorpa));
  MiniKorpa.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
  WebElement NastaviDalje = driver.findElement(By.id("top-cart-btn-checkout"));
  NastaviDalje.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("street[0]")));
  WebElement Ulica1 = driver.findElement(By.name("street[0]"));
  Ulica1.sendKeys("BlaBla 4");
  WebElement Grad1 = driver.findElement(By.name("city"));
  Grad1.sendKeys("Beograd");
  WebElement Postanski1 = driver.findElement(By.name("postcode"));
  Postanski1.sendKeys("11090");
  WebElement Fontele = driver.findElement(By.name("telephone"));
  Fontele.sendKeys("062227362");
  Thread.sleep(4000);
  JavascriptExecutor jse = (JavascriptExecutor) driver;
  jse.executeScript("window.scrollBy(0,250)");
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("intesa_payment")));
  WebElement Karticom = driver.findElement(By.id("intesa_payment"));
  Karticom.click();
  Thread.sleep(4000);
 }

 public static void KarticaIProdza2() throws InterruptedException{
  DefLogin();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img")));
  WebElement Spring = driver.findElement(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img"));
  Spring.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("product-addtocart-button")));
  WebElement DodajUKorpu = driver.findElement(By.id("product-addtocart-button"));
  DodajUKorpu.click();
  Thread.sleep(4000);
  WebElement MiniKorpa = driver.findElement(By.className("minicart-wrapper"));
  wdWait.until(ExpectedConditions.elementToBeClickable(MiniKorpa));
  MiniKorpa.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
  WebElement NastaviDalje = driver.findElement(By.id("top-cart-btn-checkout"));
  NastaviDalje.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("street[0]")));
  WebElement Ulica1 = driver.findElement(By.name("street[0]"));
  Ulica1.sendKeys("BlaBla 4");
  WebElement Grad1 = driver.findElement(By.name("city"));
  Grad1.sendKeys("Beograd");
  WebElement Postanski1 = driver.findElement(By.name("postcode"));
  Postanski1.sendKeys("11090");
  WebElement Fontele = driver.findElement(By.name("telephone"));
  Fontele.sendKeys("062227362");
  Thread.sleep(4000);
  JavascriptExecutor jse = (JavascriptExecutor) driver;
  jse.executeScript("window.scrollBy(0,250)");
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("intesa_payment")));
  WebElement Karticom = driver.findElement(By.id("intesa_payment"));
  Karticom.click();
  Thread.sleep(6000);
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("billing-address-same-as-shipping")));
  WebElement MojaAdresaista = driver.findElement(By.name("billing-address-same-as-shipping"));
  MojaAdresaista.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input")));
  WebElement NovaAdresa = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
  NovaAdresa.sendKeys("Boljevci 2");
  WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
  Grad2.sendKeys("Negotin");
  WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[8]/div/input"));
  Postanski2.sendKeys("11440");
  WebElement Fon = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
  Fon.sendKeys("062227362");
  WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[3]/div/button[1]/span"));
  Azuriraj.click();
  WebElement LicnoPreuzimanje2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[2]/li/div/div/div/div[2]/form/div[1]/table/tbody/tr[2]/td[1]/input"));
  LicnoPreuzimanje2.click();
  WebElement UsloviK = driver.findElement(By.id("agreement__1"));
  UsloviK.click();
  WebElement Kupi = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[3]/div[4]/div/div/button"));
  Kupi.click();
  Thread.sleep(4000);
 }

 public static void KarticaIProdza3() throws InterruptedException{
  DefLogin();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img")));
  WebElement Spring = driver.findElement(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img"));
  Spring.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("product-addtocart-button")));
  WebElement DodajUKorpu = driver.findElement(By.id("product-addtocart-button"));
  DodajUKorpu.click();
  Thread.sleep(4000);
  WebElement MiniKorpa = driver.findElement(By.className("minicart-wrapper"));
  wdWait.until(ExpectedConditions.elementToBeClickable(MiniKorpa));
  MiniKorpa.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
  WebElement NastaviDalje = driver.findElement(By.id("top-cart-btn-checkout"));
  NastaviDalje.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("street[0]")));
  WebElement Ulica1 = driver.findElement(By.name("street[0]"));
  Ulica1.sendKeys("BlaBla 4");
  WebElement Grad1 = driver.findElement(By.name("city"));
  Grad1.sendKeys("Beograd");
  WebElement Postanski1 = driver.findElement(By.name("postcode"));
  Postanski1.sendKeys("11090");
  WebElement Fontele = driver.findElement(By.name("telephone"));
  Fontele.sendKeys("062227362");
  Thread.sleep(4000);
  JavascriptExecutor jse = (JavascriptExecutor) driver;
  jse.executeScript("window.scrollBy(0,250)");
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("intesa_payment")));
  WebElement Karticom = driver.findElement(By.id("intesa_payment"));
  Karticom.click();
  Thread.sleep(6000);
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("billing-address-same-as-shipping")));
  WebElement MojaAdresaista = driver.findElement(By.name("billing-address-same-as-shipping"));
  MojaAdresaista.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input")));
  WebElement NovaAdresa = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
  NovaAdresa.sendKeys("Boljevci 2");
  WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
  Grad2.sendKeys("Negotin");
  WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[8]/div/input"));
  Postanski2.sendKeys("11440");
  WebElement Fon = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
  Fon.sendKeys("062227362");
  WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[3]/div/button[1]/span"));
  Azuriraj.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[2]/li/div/div/div/div[2]/form/div[1]/table/tbody/tr[3]/td[1]/input")));
  WebElement LicnoPreuzimanje3 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[2]/li/div/div/div/div[2]/form/div[1]/table/tbody/tr[3]/td[1]/input"));
  LicnoPreuzimanje3.click();
  WebElement UsloviK = driver.findElement(By.id("agreement__1"));
  UsloviK.click();
  WebElement Kupi = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[3]/div[4]/div/div/button"));
  Kupi.click();
  Thread.sleep(4000);
 }

 public static void KarticaIKurir() throws InterruptedException{
  DefLogin();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img")));
  WebElement Spring = driver.findElement(By.xpath("/html/body/div[5]/main/div[2]/div/div[5]/div/div/ol/div/div/div[3]/div/li/div/a/span/span/img"));
  Spring.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("product-addtocart-button")));
  WebElement DodajUKorpu = driver.findElement(By.id("product-addtocart-button"));
  DodajUKorpu.click();
  Thread.sleep(4000);
  WebElement MiniKorpa = driver.findElement(By.className("minicart-wrapper"));
  wdWait.until(ExpectedConditions.elementToBeClickable(MiniKorpa));
  MiniKorpa.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
  WebElement NastaviDalje = driver.findElement(By.id("top-cart-btn-checkout"));
  NastaviDalje.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("street[0]")));
  WebElement Ulica1 = driver.findElement(By.name("street[0]"));
  Ulica1.sendKeys("BlaBla 4");
  WebElement Grad1 = driver.findElement(By.name("city"));
  Grad1.sendKeys("Beograd");
  WebElement Postanski1 = driver.findElement(By.name("postcode"));
  Postanski1.sendKeys("11090");
  WebElement Fontele = driver.findElement(By.name("telephone"));
  Fontele.sendKeys("062227362");
  Thread.sleep(4000);
  JavascriptExecutor jse = (JavascriptExecutor) driver;
  jse.executeScript("window.scrollBy(0,250)");
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("intesa_payment")));
  WebElement Karticom = driver.findElement(By.id("intesa_payment"));
  Karticom.click();
  Thread.sleep(6000);
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("billing-address-same-as-shipping")));
  WebElement MojaAdresaista = driver.findElement(By.name("billing-address-same-as-shipping"));
  MojaAdresaista.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input")));
  WebElement NovaAdresa = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
  NovaAdresa.sendKeys("Boljevci 2");
  WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
  Grad2.sendKeys("Negotin");
  WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[8]/div/input"));
  Postanski2.sendKeys("11440");
  WebElement Fon = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
  Fon.sendKeys("062227362");
  WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[1]/li/div/form/fieldset/div[4]/fieldset/div[3]/div/button[1]/span"));
  Azuriraj.click();
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[2]/li/div/div/div/div[2]/form/div[1]/table/tbody/tr[3]/td[1]/input")));
  WebElement Kurir = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[2]/li/div/div/div/div[2]/form/div[1]/table/tbody/tr[4]/td[1]/input"));
  Kurir.click();
  WebElement UsloviK = driver.findElement(By.id("agreement__1"));
  UsloviK.click();
  WebElement Kupi = driver.findElement(By.xpath("/html/body/div[6]/main/div/div/div/div[5]/div[2]/div[3]/div[4]/div/div/button"));
  Kupi.click();
  Thread.sleep(4000);
 }



 public static void Search() throws InterruptedException {
  String url = "https://beocar.dev.smartweb.rs/";
  driver.navigate().to(url);
  driver.get("https://beocar.dev.smartweb.rs/");
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("q")));
  WebElement Pretraga = driver.findElement(By.name("q"));
  Pretraga.sendKeys("Ulja");
  Pretraga.sendKeys(Keys.ENTER);
  wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("amasty-shopby-product-list")));
  WebElement Rezultati = driver.findElement(By.id("amasty-shopby-product-list"));
  System.out.println(Rezultati.getText());

 }
}
