package helpers;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;



public class IluminaDEVHelper extends BaseHelper {

    public static void RegHelper() throws InterruptedException {
        String url = "https://ilumina.rs/#";
        driver.navigate().to(url);
        driver.get("https://ilumina.rs/#");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/header/div[1]/div/ul/li[5]/a")));
        WebElement RegButton = driver.findElement(By.xpath("/html/body/div[2]/header/div[1]/div/ul/li[5]/a"));
        RegButton.click();
        WebElement Ime = driver.findElement(By.name("firstname"));
        Ime.sendKeys("Nikola");
        WebElement Prezime = driver.findElement(By.name("lastname"));
        Prezime.sendKeys("Cebic");
        WebElement Email = driver.findElement(By.name("email"));
        Email.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Lozinka = driver.findElement(By.name("password"));
        Lozinka.sendKeys("Cebic123");
        WebElement Potvrda = driver.findElement(By.name("password_confirmation"));
        Potvrda.sendKeys("Cebic123");
        WebElement Aj = driver.findElement(By.xpath("/html/body/div[2]/main/div[3]/div/form/div/div[1]/button/span"));
        Aj.click();
    }

    public static void LoginHelper() throws InterruptedException{
        String url = "https://ilumina.rs/#";
        driver.navigate().to(url);
        driver.get("https://ilumina.rs/#");
        WebElement Prijava = driver.findElement(By.xpath("/html/body/div[2]/header/div[1]/div/ul/li[3]/a"));
        Prijava.click();
        WebElement Email = driver.findElement(By.name("login[username]"));
        Email.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Pass = driver.findElement(By.name("login[password]"));
        Pass.sendKeys("Cebic123");
        WebElement Ajd = driver.findElement(By.id("send2"));
        Ajd.click();

    }

    public static void KurirskaIPouzeceH() throws InterruptedException{
        String url = "https://ilumina.rs/#";
        driver.navigate().to(url);
        driver.get("https://ilumina.rs/#");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/header/div[3]/div/div[2]/nav/ul/li[3]/a/span")));
        WebElement Sijalice = driver.findElement(By.xpath("/html/body/div[2]/header/div[3]/div/div[2]/nav/ul/li[3]/a/span"));
        Sijalice.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/main/div[3]/div[1]/div[3]/div[2]/ol/li[2]/div/div[1]/a/img")));
        WebElement LEDsijalica = driver.findElement(By.xpath("/html/body/div[2]/main/div[3]/div[1]/div[3]/div[2]/ol/li[2]/div/div[1]/a/img"));
        LEDsijalica.click();
        WebElement Dodaj = driver.findElement(By.id("product-addtocart-button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Dodaj));
        Dodaj.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.className("counter-number")));
        WebElement Korpica = driver.findElement(By.className("counter-number"));
        js.executeScript("arguments[0].click();", Korpica);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
        WebElement naruci = driver.findElement(By.id("top-cart-btn-checkout"));
        naruci.click();
        Thread.sleep(3000);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement MejlPolje = driver.findElement(By.id("customer-email"));
        wdWait.until(ExpectedConditions.elementToBeClickable(MejlPolje));
        MejlPolje.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime = driver.findElement(By.name("firstname"));
        Ime.sendKeys("Nikola");
        WebElement Prezime = driver.findElement(By.name("lastname"));
        Prezime.sendKeys("Cebic");
        WebElement Adresa = driver.findElement(By.name("street[0]"));
        Adresa.sendKeys("Blabla 23");
        WebElement Grad = driver.findElement(By.name("city"));
        Grad.sendKeys("Beograd");
        WebElement Postanski = driver.findElement(By.name("postcode"));
        Postanski.sendKeys("11090");
        WebElement Fon = driver.findElement(By.name("telephone"));
        Fon.sendKeys("065789855");
        Thread.sleep(6000);

        WebElement KURIRSKA = driver.findElement(By.id("label_method_flatrate_flatrate"));
        js.executeScript("arguments[0].click();", KURIRSKA);
        WebElement Dalje = driver.findElement(By.xpath("//*[text()='Dalje']"));
        js.executeScript("arguments[0].click();", Dalje);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("cashondelivery")));
        WebElement Pouzece = driver.findElement(By.id("cashondelivery"));
        Pouzece.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("agreement_cashondelivery_1")));
        WebElement PrihvatamUslove = driver.findElement(By.id("agreement_cashondelivery_1"));
        PrihvatamUslove.click();
        WebElement MojaADR = driver.findElement(By.id("billing-address-same-as-shipping-shared"));
        MojaADR.click();
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Ime2));
        Ime2.sendKeys("Nidza");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Adresa2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Adresa2.sendKeys("Trte Mrte 2");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[4]/div/input"));
        Grad2.sendKeys("Beograd");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[7]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
        Fon2.sendKeys("065789855");
        WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[3]/div/button[1]/span"));
        Azuriraj.click();
        WebElement Poruci = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[1]/div/div/div[2]/div[2]/div[4]/div/button/span"));
        js.executeScript("arguments[0].scrollIntoView();", Poruci);
        js.executeScript("arguments[0].click();", Poruci);
    }

    public static void KurirskaIPlatnaH() throws InterruptedException{
        String url = "https://ilumina.rs/#";
        driver.navigate().to(url);
        driver.get("https://ilumina.rs/#");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/header/div[3]/div/div[2]/nav/ul/li[3]/a/span")));
        WebElement Sijalice = driver.findElement(By.xpath("/html/body/div[2]/header/div[3]/div/div[2]/nav/ul/li[3]/a/span"));
        Sijalice.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/main/div[3]/div[1]/div[3]/div[2]/ol/li[2]/div/div[1]/a/img")));
        WebElement LEDsijalica = driver.findElement(By.xpath("/html/body/div[2]/main/div[3]/div[1]/div[3]/div[2]/ol/li[2]/div/div[1]/a/img"));
        LEDsijalica.click();
        WebElement Dodaj = driver.findElement(By.id("product-addtocart-button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Dodaj));
        Dodaj.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.className("counter-number")));
        WebElement Korpica = driver.findElement(By.className("counter-number"));
        js.executeScript("arguments[0].click();", Korpica);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
        WebElement naruci = driver.findElement(By.id("top-cart-btn-checkout"));
        naruci.click();
        Thread.sleep(3000);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement MejlPolje = driver.findElement(By.id("customer-email"));
        wdWait.until(ExpectedConditions.elementToBeClickable(MejlPolje));
        MejlPolje.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime = driver.findElement(By.name("firstname"));
        Ime.sendKeys("Nikola");
        WebElement Prezime = driver.findElement(By.name("lastname"));
        Prezime.sendKeys("Cebic");
        WebElement Adresa = driver.findElement(By.name("street[0]"));
        Adresa.sendKeys("Blabla 23");
        WebElement Grad = driver.findElement(By.name("city"));
        Grad.sendKeys("Beograd");
        WebElement Postanski = driver.findElement(By.name("postcode"));
        Postanski.sendKeys("11090");
        WebElement Fon = driver.findElement(By.name("telephone"));
        Fon.sendKeys("065789855");
        Thread.sleep(3000);
        WebElement KURIRSKA = driver.findElement(By.id("label_method_flatrate_flatrate"));
        js.executeScript("arguments[0].click();", KURIRSKA);
        WebElement Dalje = driver.findElement(By.xpath("//*[text()='Dalje']"));
        js.executeScript("arguments[0].click();", Dalje);

        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("sample_gateway")));
        WebElement Platna = driver.findElement(By.id("sample_gateway"));
        js.executeScript("arguments[0].click();", Platna);
        WebElement Prihvacam = driver.findElement(By.id("agreement_sample_gateway_1"));
        Prihvacam.click();
        WebElement MojaADR = driver.findElement(By.id("billing-address-same-as-shipping-shared"));
        MojaADR.click();
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        Ime2.sendKeys("Nikola");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Adresa2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Adresa2.sendKeys("Trte Mrte 23");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[4]/div/input"));
        Grad2.sendKeys("Beograd");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[7]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
        Fon2.sendKeys("067789853");
        WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[3]/div/button[1]/span"));
        Azuriraj.click();
        WebElement Poruci = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[1]/div/div/div[3]/div[2]/div[4]/div/button/span"));
        js.executeScript("arguments[0].scrollIntoView();", Poruci);
        js.executeScript("arguments[0].click();", Poruci);

    }

    public static void KurirskaILicnoH() throws InterruptedException{
        String url = "https://ilumina.rs/#";
        driver.navigate().to(url);
        driver.get("https://ilumina.rs/#");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/header/div[3]/div/div[2]/nav/ul/li[3]/a/span")));
        WebElement Sijalice = driver.findElement(By.xpath("/html/body/div[2]/header/div[3]/div/div[2]/nav/ul/li[3]/a/span"));
        Sijalice.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/main/div[3]/div[1]/div[3]/div[2]/ol/li[2]/div/div[1]/a/img")));
        WebElement LEDsijalica = driver.findElement(By.xpath("/html/body/div[2]/main/div[3]/div[1]/div[3]/div[2]/ol/li[2]/div/div[1]/a/img"));
        LEDsijalica.click();
        WebElement Dodaj = driver.findElement(By.id("product-addtocart-button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Dodaj));
        Dodaj.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.className("counter-number")));
        WebElement Korpica = driver.findElement(By.className("counter-number"));
        js.executeScript("arguments[0].click();", Korpica);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
        WebElement naruci = driver.findElement(By.id("top-cart-btn-checkout"));
        naruci.click();
        Thread.sleep(3000);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement MejlPolje = driver.findElement(By.id("customer-email"));
        wdWait.until(ExpectedConditions.elementToBeClickable(MejlPolje));
        MejlPolje.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime = driver.findElement(By.name("firstname"));
        Ime.sendKeys("Nikola");
        WebElement Prezime = driver.findElement(By.name("lastname"));
        Prezime.sendKeys("Cebic");
        WebElement Adresa = driver.findElement(By.name("street[0]"));
        Adresa.sendKeys("Blabla 23");
        WebElement Grad = driver.findElement(By.name("city"));
        Grad.sendKeys("Beograd");
        WebElement Postanski = driver.findElement(By.name("postcode"));
        Postanski.sendKeys("11090");
        WebElement Fon = driver.findElement(By.name("telephone"));
        Fon.sendKeys("065789855");
        Thread.sleep(6000);

        WebElement KURIRSKA = driver.findElement(By.id("label_method_flatrate_flatrate"));
        js.executeScript("arguments[0].click();", KURIRSKA);
        WebElement Dalje = driver.findElement(By.xpath("//*[text()='Dalje']"));
        js.executeScript("arguments[0].click();", Dalje);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("checkmo")));
        WebElement LicnoPlacanje = driver.findElement(By.id("checkmo"));
        js.executeScript("arguments[0].click();", LicnoPlacanje);
        WebElement Prihvacam = driver.findElement(By.id("agreement_checkmo_1"));
        Prihvacam.click();
        WebElement MojaADR = driver.findElement(By.id("billing-address-same-as-shipping-shared"));
        MojaADR.click();
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        Ime2.sendKeys("Nidza");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Adresa2= driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Adresa2.sendKeys("Trte Mrte 2 ");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[4]/div/input"));
        Grad2.sendKeys("Beograd");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[7]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
        Fon2.sendKeys("065455565");
        WebElement Azuiriraj = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[3]/div/button[1]/span"));
        Azuiriraj.click();
        WebElement Poruci = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[1]/div/div/div[4]/div[2]/div[3]/div/button/span"));
        js.executeScript("arguments[0].scrollIntoView();", Poruci);
        js.executeScript("arguments[0].click();", Poruci);
    }

    public static void KurirskaIPrekoRacuna() throws InterruptedException{
        String url = "https://ilumina.rs/#";
        driver.navigate().to(url);
        driver.get("https://ilumina.rs/#");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/header/div[3]/div/div[2]/nav/ul/li[3]/a/span")));
        WebElement Sijalice = driver.findElement(By.xpath("/html/body/div[2]/header/div[3]/div/div[2]/nav/ul/li[3]/a/span"));
        Sijalice.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/main/div[3]/div[1]/div[3]/div[2]/ol/li[2]/div/div[1]/a/img")));
        WebElement LEDsijalica = driver.findElement(By.xpath("/html/body/div[2]/main/div[3]/div[1]/div[3]/div[2]/ol/li[2]/div/div[1]/a/img"));
        LEDsijalica.click();
        WebElement Dodaj = driver.findElement(By.id("product-addtocart-button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Dodaj));
        Dodaj.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.className("counter-number")));
        WebElement Korpica = driver.findElement(By.className("counter-number"));
        js.executeScript("arguments[0].click();", Korpica);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
        WebElement naruci = driver.findElement(By.id("top-cart-btn-checkout"));
        naruci.click();
        Thread.sleep(3000);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement MejlPolje = driver.findElement(By.id("customer-email"));
        wdWait.until(ExpectedConditions.elementToBeClickable(MejlPolje));
        MejlPolje.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime = driver.findElement(By.name("firstname"));
        Ime.sendKeys("Nikola");
        WebElement Prezime = driver.findElement(By.name("lastname"));
        Prezime.sendKeys("Cebic");
        WebElement Adresa = driver.findElement(By.name("street[0]"));
        Adresa.sendKeys("Blabla 23");
        WebElement Grad = driver.findElement(By.name("city"));
        Grad.sendKeys("Beograd");
        WebElement Postanski = driver.findElement(By.name("postcode"));
        Postanski.sendKeys("11090");
        WebElement Fon = driver.findElement(By.name("telephone"));
        Fon.sendKeys("065789855");
        Thread.sleep(6000);

        WebElement KURIRSKA = driver.findElement(By.id("label_method_flatrate_flatrate"));
        js.executeScript("arguments[0].click();", KURIRSKA);
        WebElement Dalje = driver.findElement(By.xpath("//*[text()='Dalje']"));
        js.executeScript("arguments[0].click();", Dalje);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("banktransfer")));
        WebElement Racun = driver.findElement(By.id("banktransfer"));
        js.executeScript("arguments[0].click();", Racun);
        WebElement Prihvacam = driver.findElement(By.id("agreement_banktransfer_1"));
        Prihvacam.click();
        WebElement MojaADR = driver.findElement(By.id("billing-address-same-as-shipping-shared"));
        js.executeScript("arguments[0].click();", MojaADR);
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        Ime2.sendKeys("Nidza");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Adresa2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Adresa2.sendKeys("Trte Mrte 3");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[4]/div/input"));
        Grad2.sendKeys("Beograd");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[7]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
        Fon2.sendKeys("068753355");
        WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[3]/div/button[1]/span"));
        Azuriraj.click();
        WebElement Poruci = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[1]/div/div/div[5]/div[2]/div[4]/div/button/span"));
        js.executeScript("arguments[0].scrollIntoView();", Poruci);
        js.executeScript("arguments[0].click();", Poruci);
    }

    public static void LicnoIPouzeceH() throws InterruptedException{
        String url = "https://ilumina.rs/#";
        driver.navigate().to(url);
        driver.get("https://ilumina.rs/#");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/header/div[3]/div/div[2]/nav/ul/li[3]/a/span")));
        WebElement Sijalice = driver.findElement(By.xpath("/html/body/div[2]/header/div[3]/div/div[2]/nav/ul/li[3]/a/span"));
        Sijalice.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/main/div[3]/div[1]/div[3]/div[2]/ol/li[2]/div/div[1]/a/img")));
        WebElement LEDsijalica = driver.findElement(By.xpath("/html/body/div[2]/main/div[3]/div[1]/div[3]/div[2]/ol/li[2]/div/div[1]/a/img"));
        LEDsijalica.click();
        WebElement Dodaj = driver.findElement(By.id("product-addtocart-button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Dodaj));
        Dodaj.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.className("counter-number")));
        WebElement Korpica = driver.findElement(By.className("counter-number"));
        js.executeScript("arguments[0].click();", Korpica);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
        WebElement naruci = driver.findElement(By.id("top-cart-btn-checkout"));
        naruci.click();
        Thread.sleep(3000);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement MejlPolje = driver.findElement(By.id("customer-email"));
        wdWait.until(ExpectedConditions.elementToBeClickable(MejlPolje));
        MejlPolje.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime = driver.findElement(By.name("firstname"));
        Ime.sendKeys("Nikola");
        WebElement Prezime = driver.findElement(By.name("lastname"));
        Prezime.sendKeys("Cebic");
        WebElement Adresa = driver.findElement(By.name("street[0]"));
        Adresa.sendKeys("Blabla 23");
        WebElement Grad = driver.findElement(By.name("city"));
        Grad.sendKeys("Beograd");
        WebElement Postanski = driver.findElement(By.name("postcode"));
        Postanski.sendKeys("11090");
        WebElement Fon = driver.findElement(By.name("telephone"));
        Fon.sendKeys("065789855");
        Thread.sleep(6000);
        WebElement LICNO_PREUZIMANJE = driver.findElement(By.id("label_method_freeshipping_freeshipping"));
        js.executeScript("arguments[0].click();", LICNO_PREUZIMANJE);
        WebElement Dalje = driver.findElement(By.xpath("//*[text()='Dalje']"));
        js.executeScript("arguments[0].click();", Dalje);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("cashondelivery")));
        WebElement Pouzece = driver.findElement(By.id("cashondelivery"));
        Pouzece.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("agreement_cashondelivery_1")));
        WebElement PrihvatamUslove = driver.findElement(By.id("agreement_cashondelivery_1"));
        PrihvatamUslove.click();
        WebElement MojaADR = driver.findElement(By.id("billing-address-same-as-shipping-shared"));
        MojaADR.click();
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Ime2));
        Ime2.sendKeys("Nidza");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Adresa2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Adresa2.sendKeys("Trte Mrte 2");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[4]/div/input"));
        Grad2.sendKeys("Beograd");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[7]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
        Fon2.sendKeys("065789855");
        WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[3]/div/button[1]/span"));
        Azuriraj.click();
        WebElement Poruci = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[1]/div/div/div[2]/div[2]/div[4]/div/button/span"));
        js.executeScript("arguments[0].scrollIntoView();", Poruci);
        js.executeScript("arguments[0].click();", Poruci);
    }

    public static void LicnoIPlatnaH() throws InterruptedException{
        String url = "https://ilumina.rs/#";
        driver.navigate().to(url);
        driver.get("https://ilumina.rs/#");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/header/div[3]/div/div[2]/nav/ul/li[3]/a/span")));
        WebElement Sijalice = driver.findElement(By.xpath("/html/body/div[2]/header/div[3]/div/div[2]/nav/ul/li[3]/a/span"));
        Sijalice.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/main/div[3]/div[1]/div[3]/div[2]/ol/li[2]/div/div[1]/a/img")));
        WebElement LEDsijalica = driver.findElement(By.xpath("/html/body/div[2]/main/div[3]/div[1]/div[3]/div[2]/ol/li[2]/div/div[1]/a/img"));
        LEDsijalica.click();
        WebElement Dodaj = driver.findElement(By.id("product-addtocart-button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Dodaj));
        Dodaj.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.className("counter-number")));
        WebElement Korpica = driver.findElement(By.className("counter-number"));
        js.executeScript("arguments[0].click();", Korpica);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
        WebElement naruci = driver.findElement(By.id("top-cart-btn-checkout"));
        naruci.click();
        Thread.sleep(3000);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement MejlPolje = driver.findElement(By.id("customer-email"));
        wdWait.until(ExpectedConditions.elementToBeClickable(MejlPolje));
        MejlPolje.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime = driver.findElement(By.name("firstname"));
        Ime.sendKeys("Nikola");
        WebElement Prezime = driver.findElement(By.name("lastname"));
        Prezime.sendKeys("Cebic");
        WebElement Adresa = driver.findElement(By.name("street[0]"));
        Adresa.sendKeys("Blabla 23");
        WebElement Grad = driver.findElement(By.name("city"));
        Grad.sendKeys("Beograd");
        WebElement Postanski = driver.findElement(By.name("postcode"));
        Postanski.sendKeys("11090");
        WebElement Fon = driver.findElement(By.name("telephone"));
        Fon.sendKeys("065789855");
        Thread.sleep(6000);
        WebElement LICNO_PREUZIMANJE = driver.findElement(By.id("label_method_freeshipping_freeshipping"));
        js.executeScript("arguments[0].click();", LICNO_PREUZIMANJE);
        WebElement Dalje = driver.findElement(By.xpath("//*[text()='Dalje']"));
        js.executeScript("arguments[0].click();", Dalje);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("sample_gateway")));
        WebElement Platna = driver.findElement(By.id("sample_gateway"));
        js.executeScript("arguments[0].click();", Platna);
        WebElement Prihvacam = driver.findElement(By.id("agreement_sample_gateway_1"));
        Prihvacam.click();
        WebElement MojaADR = driver.findElement(By.id("billing-address-same-as-shipping-shared"));
        MojaADR.click();
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        Ime2.sendKeys("Nikola");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Adresa2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Adresa2.sendKeys("Trte Mrte 23");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[4]/div/input"));
        Grad2.sendKeys("Beograd");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[7]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
        Fon2.sendKeys("067789853");
        WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[3]/div/button[1]/span"));
        Azuriraj.click();
        WebElement Poruci = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[1]/div/div/div[3]/div[2]/div[4]/div/button/span"));
        js.executeScript("arguments[0].scrollIntoView();", Poruci);
        js.executeScript("arguments[0].click();", Poruci);
    }

    public static void LicnoILicnoPH() throws InterruptedException{
        String url = "https://ilumina.rs/#";
        driver.navigate().to(url);
        driver.get("https://ilumina.rs/#");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/header/div[3]/div/div[2]/nav/ul/li[3]/a/span")));
        WebElement Sijalice = driver.findElement(By.xpath("/html/body/div[2]/header/div[3]/div/div[2]/nav/ul/li[3]/a/span"));
        Sijalice.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/main/div[3]/div[1]/div[3]/div[2]/ol/li[2]/div/div[1]/a/img")));
        WebElement LEDsijalica = driver.findElement(By.xpath("/html/body/div[2]/main/div[3]/div[1]/div[3]/div[2]/ol/li[2]/div/div[1]/a/img"));
        LEDsijalica.click();
        WebElement Dodaj = driver.findElement(By.id("product-addtocart-button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Dodaj));
        Dodaj.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.className("counter-number")));
        WebElement Korpica = driver.findElement(By.className("counter-number"));
        js.executeScript("arguments[0].click();", Korpica);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
        WebElement naruci = driver.findElement(By.id("top-cart-btn-checkout"));
        naruci.click();
        Thread.sleep(3000);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement MejlPolje = driver.findElement(By.id("customer-email"));
        wdWait.until(ExpectedConditions.elementToBeClickable(MejlPolje));
        MejlPolje.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime = driver.findElement(By.name("firstname"));
        Ime.sendKeys("Nikola");
        WebElement Prezime = driver.findElement(By.name("lastname"));
        Prezime.sendKeys("Cebic");
        WebElement Adresa = driver.findElement(By.name("street[0]"));
        Adresa.sendKeys("Blabla 23");
        WebElement Grad = driver.findElement(By.name("city"));
        Grad.sendKeys("Beograd");
        WebElement Postanski = driver.findElement(By.name("postcode"));
        Postanski.sendKeys("11090");
        WebElement Fon = driver.findElement(By.name("telephone"));
        Fon.sendKeys("065789855");
        Thread.sleep(6000);
        WebElement LICNO_PREUZIMANJE = driver.findElement(By.id("label_method_freeshipping_freeshipping"));
        js.executeScript("arguments[0].click();", LICNO_PREUZIMANJE);
        WebElement Dalje = driver.findElement(By.xpath("//*[text()='Dalje']"));
        js.executeScript("arguments[0].click();", Dalje);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("checkmo")));
        WebElement LicnoPlacanje = driver.findElement(By.id("checkmo"));
        js.executeScript("arguments[0].click();", LicnoPlacanje);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("agreement_checkmo_1")));
        WebElement Prihvacam = driver.findElement(By.id("agreement_checkmo_1"));
        Prihvacam.click();
        WebElement MojaADR = driver.findElement(By.id("billing-address-same-as-shipping-shared"));
        MojaADR.click();
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        Ime2.sendKeys("Nidza");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Adresa2= driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Adresa2.sendKeys("Trte Mrte 2 ");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[4]/div/input"));
        Grad2.sendKeys("Beograd");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[7]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
        Fon2.sendKeys("065455565");
        WebElement Azuiriraj = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[3]/div/button[1]/span"));
        Azuiriraj.click();
        WebElement Poruci = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[1]/div/div/div[4]/div[2]/div[3]/div/button/span"));
        js.executeScript("arguments[0].scrollIntoView();", Poruci);
        js.executeScript("arguments[0].click();", Poruci);
    }

    public static void LicnoiUplataH() throws InterruptedException{
        String url = "https://ilumina.rs/#";
        driver.navigate().to(url);
        driver.get("https://ilumina.rs/#");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/header/div[3]/div/div[2]/nav/ul/li[3]/a/span")));
        WebElement Sijalice = driver.findElement(By.xpath("/html/body/div[2]/header/div[3]/div/div[2]/nav/ul/li[3]/a/span"));
        Sijalice.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/main/div[3]/div[1]/div[3]/div[2]/ol/li[2]/div/div[1]/a/img")));
        WebElement LEDsijalica = driver.findElement(By.xpath("/html/body/div[2]/main/div[3]/div[1]/div[3]/div[2]/ol/li[2]/div/div[1]/a/img"));
        LEDsijalica.click();
        WebElement Dodaj = driver.findElement(By.id("product-addtocart-button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Dodaj));
        Dodaj.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.className("counter-number")));
        WebElement Korpica = driver.findElement(By.className("counter-number"));
        js.executeScript("arguments[0].click();", Korpica);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("top-cart-btn-checkout")));
        WebElement naruci = driver.findElement(By.id("top-cart-btn-checkout"));
        naruci.click();
        Thread.sleep(3000);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement MejlPolje = driver.findElement(By.id("customer-email"));
        wdWait.until(ExpectedConditions.elementToBeClickable(MejlPolje));
        MejlPolje.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime = driver.findElement(By.name("firstname"));
        Ime.sendKeys("Nikola");
        WebElement Prezime = driver.findElement(By.name("lastname"));
        Prezime.sendKeys("Cebic");
        WebElement Adresa = driver.findElement(By.name("street[0]"));
        Adresa.sendKeys("Blabla 23");
        WebElement Grad = driver.findElement(By.name("city"));
        Grad.sendKeys("Beograd");
        WebElement Postanski = driver.findElement(By.name("postcode"));
        Postanski.sendKeys("11090");
        WebElement Fon = driver.findElement(By.name("telephone"));
        Fon.sendKeys("065789855");
        Thread.sleep(6000);
        WebElement LICNO_PREUZIMANJE = driver.findElement(By.id("label_method_freeshipping_freeshipping"));
        js.executeScript("arguments[0].click();", LICNO_PREUZIMANJE);
        WebElement Dalje = driver.findElement(By.xpath("//*[text()='Dalje']"));
        js.executeScript("arguments[0].click();", Dalje);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("banktransfer")));
        WebElement Racun = driver.findElement(By.id("banktransfer"));
        js.executeScript("arguments[0].click();", Racun);
        WebElement Prihvacam = driver.findElement(By.id("agreement_banktransfer_1"));
        Prihvacam.click();
        WebElement MojaADR = driver.findElement(By.id("billing-address-same-as-shipping-shared"));
        js.executeScript("arguments[0].click();", MojaADR);
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        Ime2.sendKeys("Nidza");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Adresa2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Adresa2.sendKeys("Trte Mrte 3");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[4]/div/input"));
        Grad2.sendKeys("Beograd");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[7]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[2]/div/form/fieldset/div[9]/div/input"));
        Fon2.sendKeys("068753355");
        WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[3]/fieldset/div[3]/div/button[1]/span"));
        Azuriraj.click();
        WebElement Poruci = driver.findElement(By.xpath("/html/body/div[3]/main/div[2]/div/div[2]/div[4]/ol/li[3]/div/form/fieldset/div[1]/div/div/div[5]/div[2]/div[4]/div/button/span"));
        js.executeScript("arguments[0].scrollIntoView();", Poruci);
        js.executeScript("arguments[0].click();", Poruci);
    }

    public static void SearchH() throws InterruptedException{
        String url = "https://ilumina.rs/#";
        driver.navigate().to(url);
        driver.get("https://ilumina.rs/#");
        WebElement SearchPolje = driver.findElement(By.id("search"));
        SearchPolje.click();
        SearchPolje.sendKeys("Sijalice");
        SearchPolje.sendKeys(Keys.ENTER);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("layer-product-list")));
        WebElement Result = driver.findElement(By.id("layer-product-list"));
        System.out.println(Result.getText());


    }
}
