package helpers;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;

public class MieleDevHelper extends BaseHelper {

    public static void RegHelper() throws InterruptedException {
        String url = "https://miele.dev.smartweb.rs/";
        driver.navigate().to(url);
        driver.get("https://miele.dev.smartweb.rs/");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/header/div/div/div[1]/div[2]/ul/li[3]/a")));
        WebElement Nalog = driver.findElement(By.xpath("/html/body/div[5]/header/div/div/div[1]/div[2]/ul/li[3]/a"));
        Nalog.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[3]/div/div[2]/div[2]/div[2]/div/div/a/span")));
        WebElement Regbutton = driver.findElement(By.xpath("/html/body/div[5]/main/div[3]/div/div[2]/div[2]/div[2]/div/div/a/span"));
        Regbutton.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("firstname")));
        WebElement Ime = driver.findElement(By.name("firstname"));
        Ime.sendKeys("Nikola");
        WebElement Prezime = driver.findElement(By.name("lastname"));
        Prezime.sendKeys("Cebic");
        WebElement Email = driver.findElement(By.name("email"));
        Email.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Pass = driver.findElement(By.name("password"));
        Pass.sendKeys("Cebic123");
        WebElement Potvrda = driver.findElement(By.name("password_confirmation"));
        Potvrda.sendKeys("Cebic123");
        WebElement RegFinal = driver.findElement(By.xpath("/html/body/div[5]/main/div[3]/div/form/div/div[1]/button/span"));
        js.executeScript("arguments[0].click();", RegFinal);

    }

    public static void LoginHelper() throws InterruptedException {
        String url = "https://miele.dev.smartweb.rs/";
        driver.navigate().to(url);
        driver.get("https://miele.dev.smartweb.rs/");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/header/div/div/div[1]/div[2]/ul/li[3]/a")));
        WebElement Nalog = driver.findElement(By.xpath("/html/body/div[5]/header/div/div/div[1]/div[2]/ul/li[3]/a"));
        Nalog.click();
        WebElement Mejl = driver.findElement(By.name("login[username]"));
        Mejl.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Pass = driver.findElement(By.name("login[password]"));
        Pass.sendKeys("Cebic123");
        WebElement Aj = driver.findElement(By.id("send2"));
        Aj.click();
    }

    public static void KurirskaiGotovina() throws InterruptedException {
        String url = "https://miele.dev.smartweb.rs/";
        driver.navigate().to(url);
        driver.get("https://miele.dev.smartweb.rs/");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/div[1]/nav/ul[1]/li[3]/a/span[2]")));
        WebElement NegaVesa = driver.findElement(By.xpath("/html/body/div[5]/div[1]/nav/ul[1]/li[3]/a/span[2]"));
        NegaVesa.click();
        Select Sorter = new Select(driver.findElement(By.id("sorter")));
        Sorter.selectByVisibleText("Cena");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[3]/div[1]/div[5]/div[2]/ol/li[1]/div/a/span/span/img")));
        WebElement Kapsula = driver.findElement(By.xpath("/html/body/div[5]/main/div[3]/div[1]/div[5]/div[2]/ol/li[1]/div/a/span/span/img"));
        Kapsula.click();
        WebElement Dodaj = driver.findElement(By.id("product-addtocart-button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Dodaj));
        Dodaj.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[1]/div[2]/div/div/div/a")));
        WebElement MiniK = driver.findElement(By.xpath("/html/body/div[5]/main/div[1]/div[2]/div/div/div/a"));
        MiniK.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[3]/div/div[2]/div[1]/ul/li[1]/button")));
        WebElement NastaviP = driver.findElement(By.xpath("/html/body/div[5]/main/div[3]/div/div[2]/div[1]/ul/li[1]/button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(NastaviP));
        NastaviP.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement Mejl = driver.findElement(By.id("customer-email"));
        Mejl.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime1 = driver.findElement(By.name("firstname"));
        Ime1.sendKeys("Nikola");
        WebElement Prezime1 = driver.findElement(By.name("lastname"));
        Prezime1.sendKeys("Cebic");
        WebElement Postanski1 = driver.findElement(By.name("postcode"));
        Postanski1.sendKeys("11090");
        WebElement Grad1 = driver.findElement(By.name("city"));
        Grad1.sendKeys("Beograd");
        WebElement Ulica1 = driver.findElement(By.name("street[0]"));
        Ulica1.sendKeys("Blabla 23");
        WebElement Fon1 = driver.findElement(By.name("telephone"));
        Fon1.sendKeys("065789562");
        WebElement MojaAdresa = driver.findElement(By.name("billing-address-same-as-shipping"));
        js.executeScript("arguments[0].click();", MojaAdresa);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input")));
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        Ime2.sendKeys("Nikola");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[6]/div/input"));
        Grad2.sendKeys("Beograd");
        WebElement Ulica2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Ulica2.sendKeys("Trte Mrte 23");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[7]/div/input"));
        Fon2.sendKeys("0684555665");
        WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[3]/div/button[1]/span"));
        js.executeScript("arguments[0].click();", Azuriraj);
        Thread.sleep(8000);
        WebElement KURIRSKA_ISPORUKA = driver.findElement(By.id("s_method_tablerate_bestway"));
        wdWait.until(ExpectedConditions.elementToBeClickable(KURIRSKA_ISPORUKA));
        KURIRSKA_ISPORUKA.click();
        WebElement GOTOVINA = driver.findElement(By.id("cashondelivery"));
        wdWait.until(ExpectedConditions.elementToBeClickable(GOTOVINA));
        js.executeScript("arguments[0].click();", GOTOVINA);
        WebElement Saglasnost = driver.findElement(By.name("agreement[1]"));
        js.executeScript("arguments[0].click();", Saglasnost);
        Thread.sleep(5000);
       //WebElement Kupi = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[2]/div[2]/div[4]/div/div/button"));
        //Kupi.click();
    }

    public static void KurirskaIPreracun() throws InterruptedException{
        String url = "https://miele.dev.smartweb.rs/";
        driver.navigate().to(url);
        driver.get("https://miele.dev.smartweb.rs/");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/div[1]/nav/ul[1]/li[3]/a/span[2]")));
        WebElement NegaVesa = driver.findElement(By.xpath("/html/body/div[5]/div[1]/nav/ul[1]/li[3]/a/span[2]"));
        NegaVesa.click();
        Select Sorter = new Select(driver.findElement(By.id("sorter")));
        Sorter.selectByVisibleText("Cena");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[3]/div[1]/div[5]/div[2]/ol/li[1]/div/a/span/span/img")));
        WebElement Kapsula = driver.findElement(By.xpath("/html/body/div[5]/main/div[3]/div[1]/div[5]/div[2]/ol/li[1]/div/a/span/span/img"));
        Kapsula.click();
        WebElement Dodaj = driver.findElement(By.id("product-addtocart-button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Dodaj));
        Dodaj.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[1]/div[2]/div/div/div/a")));
        WebElement MiniK = driver.findElement(By.xpath("/html/body/div[5]/main/div[1]/div[2]/div/div/div/a"));
        MiniK.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[3]/div/div[2]/div[1]/ul/li[1]/button")));
        WebElement NastaviP = driver.findElement(By.xpath("/html/body/div[5]/main/div[3]/div/div[2]/div[1]/ul/li[1]/button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(NastaviP));
        NastaviP.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement Mejl = driver.findElement(By.id("customer-email"));
        Mejl.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime1 = driver.findElement(By.name("firstname"));
        Ime1.sendKeys("Nikola");
        WebElement Prezime1 = driver.findElement(By.name("lastname"));
        Prezime1.sendKeys("Cebic");
        WebElement Postanski1 = driver.findElement(By.name("postcode"));
        Postanski1.sendKeys("11090");
        WebElement Grad1 = driver.findElement(By.name("city"));
        Grad1.sendKeys("Beograd");
        WebElement Ulica1 = driver.findElement(By.name("street[0]"));
        Ulica1.sendKeys("Blabla 23");
        WebElement Fon1 = driver.findElement(By.name("telephone"));
        Fon1.sendKeys("065789562");
        WebElement MojaAdresa = driver.findElement(By.name("billing-address-same-as-shipping"));
        js.executeScript("arguments[0].click();", MojaAdresa);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input")));
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        Ime2.sendKeys("Nikola");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[6]/div/input"));
        Grad2.sendKeys("Beograd");
        WebElement Ulica2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Ulica2.sendKeys("Trte Mrte 23");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[7]/div/input"));
        Fon2.sendKeys("0684555665");
        WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[3]/div/button[1]/span"));
        js.executeScript("arguments[0].click();", Azuriraj);
        Thread.sleep(8000);
        WebElement KURIRSKA_ISPORUKA = driver.findElement(By.id("s_method_tablerate_bestway"));
        wdWait.until(ExpectedConditions.elementToBeClickable(KURIRSKA_ISPORUKA));
        KURIRSKA_ISPORUKA.click();
        WebElement PRERACUN = driver.findElement(By.id("checkmo"));
        wdWait.until(ExpectedConditions.elementToBeClickable(PRERACUN));
        js.executeScript("arguments[0].click();", PRERACUN);
        WebElement Saglasnost = driver.findElement(By.name("agreement[1]"));
        js.executeScript("arguments[0].click();", Saglasnost);
        Thread.sleep(5000);
        //WebElement Kupi = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[2]/div[2]/div[4]/div/div/button"));
        //Kupi.click();
    }

    public static void KurirskaIKupovinanarate() throws InterruptedException{
        String url = "https://miele.dev.smartweb.rs/";
        driver.navigate().to(url);
        driver.get("https://miele.dev.smartweb.rs/");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/div[1]/nav/ul[1]/li[3]/a/span[2]")));
        WebElement NegaVesa = driver.findElement(By.xpath("/html/body/div[5]/div[1]/nav/ul[1]/li[3]/a/span[2]"));
        NegaVesa.click();
        Select Sorter = new Select(driver.findElement(By.id("sorter")));
        Sorter.selectByVisibleText("Cena");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[3]/div[1]/div[5]/div[2]/ol/li[1]/div/a/span/span/img")));
        WebElement Kapsula = driver.findElement(By.xpath("/html/body/div[5]/main/div[3]/div[1]/div[5]/div[2]/ol/li[1]/div/a/span/span/img"));
        Kapsula.click();
        WebElement Dodaj = driver.findElement(By.id("product-addtocart-button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Dodaj));
        Dodaj.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[1]/div[2]/div/div/div/a")));
        WebElement MiniK = driver.findElement(By.xpath("/html/body/div[5]/main/div[1]/div[2]/div/div/div/a"));
        MiniK.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[3]/div/div[2]/div[1]/ul/li[1]/button")));
        WebElement NastaviP = driver.findElement(By.xpath("/html/body/div[5]/main/div[3]/div/div[2]/div[1]/ul/li[1]/button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(NastaviP));
        NastaviP.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement Mejl = driver.findElement(By.id("customer-email"));
        Mejl.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime1 = driver.findElement(By.name("firstname"));
        Ime1.sendKeys("Nikola");
        WebElement Prezime1 = driver.findElement(By.name("lastname"));
        Prezime1.sendKeys("Cebic");
        WebElement Postanski1 = driver.findElement(By.name("postcode"));
        Postanski1.sendKeys("11090");
        WebElement Grad1 = driver.findElement(By.name("city"));
        Grad1.sendKeys("Beograd");
        WebElement Ulica1 = driver.findElement(By.name("street[0]"));
        Ulica1.sendKeys("Blabla 23");
        WebElement Fon1 = driver.findElement(By.name("telephone"));
        Fon1.sendKeys("065789562");
        WebElement MojaAdresa = driver.findElement(By.name("billing-address-same-as-shipping"));
        js.executeScript("arguments[0].click();", MojaAdresa);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input")));
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        Ime2.sendKeys("Nikola");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[6]/div/input"));
        Grad2.sendKeys("Beograd");
        WebElement Ulica2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Ulica2.sendKeys("Trte Mrte 23");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[7]/div/input"));
        Fon2.sendKeys("0684555665");
        WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[3]/div/button[1]/span"));
        js.executeScript("arguments[0].click();", Azuriraj);
        Thread.sleep(8000);
        WebElement KURIRSKA_ISPORUKA = driver.findElement(By.id("s_method_tablerate_bestway"));
        wdWait.until(ExpectedConditions.elementToBeClickable(KURIRSKA_ISPORUKA));
        KURIRSKA_ISPORUKA.click();
        WebElement KUPOVINANARATE = driver.findElement(By.id("banktransfer"));
        wdWait.until(ExpectedConditions.elementToBeClickable(KUPOVINANARATE));
        js.executeScript("arguments[0].click();", KUPOVINANARATE);
        WebElement Saglasnost = driver.findElement(By.name("agreement[1]"));
        js.executeScript("arguments[0].click();", Saglasnost);
        Thread.sleep(5000);
        //WebElement Kupi = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[2]/div[2]/div[4]/div/div/button"));
        //Kupi.click();
    }

    public static void LicnaIGotovina() throws InterruptedException{
        String url = "https://miele.dev.smartweb.rs/";
        driver.navigate().to(url);
        driver.get("https://miele.dev.smartweb.rs/");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/div[1]/nav/ul[1]/li[3]/a/span[2]")));
        WebElement NegaVesa = driver.findElement(By.xpath("/html/body/div[5]/div[1]/nav/ul[1]/li[3]/a/span[2]"));
        NegaVesa.click();
        Select Sorter = new Select(driver.findElement(By.id("sorter")));
        Sorter.selectByVisibleText("Cena");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[3]/div[1]/div[5]/div[2]/ol/li[1]/div/a/span/span/img")));
        WebElement Kapsula = driver.findElement(By.xpath("/html/body/div[5]/main/div[3]/div[1]/div[5]/div[2]/ol/li[1]/div/a/span/span/img"));
        Kapsula.click();
        WebElement Dodaj = driver.findElement(By.id("product-addtocart-button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Dodaj));
        Dodaj.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[1]/div[2]/div/div/div/a")));
        WebElement MiniK = driver.findElement(By.xpath("/html/body/div[5]/main/div[1]/div[2]/div/div/div/a"));
        MiniK.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[3]/div/div[2]/div[1]/ul/li[1]/button")));
        WebElement NastaviP = driver.findElement(By.xpath("/html/body/div[5]/main/div[3]/div/div[2]/div[1]/ul/li[1]/button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(NastaviP));
        NastaviP.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement Mejl = driver.findElement(By.id("customer-email"));
        Mejl.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime1 = driver.findElement(By.name("firstname"));
        Ime1.sendKeys("Nikola");
        WebElement Prezime1 = driver.findElement(By.name("lastname"));
        Prezime1.sendKeys("Cebic");
        WebElement Postanski1 = driver.findElement(By.name("postcode"));
        Postanski1.sendKeys("11090");
        WebElement Grad1 = driver.findElement(By.name("city"));
        Grad1.sendKeys("Beograd");
        WebElement Ulica1 = driver.findElement(By.name("street[0]"));
        Ulica1.sendKeys("Blabla 23");
        WebElement Fon1 = driver.findElement(By.name("telephone"));
        Fon1.sendKeys("065789562");
        WebElement MojaAdresa = driver.findElement(By.name("billing-address-same-as-shipping"));
        js.executeScript("arguments[0].click();", MojaAdresa);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input")));
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        Ime2.sendKeys("Nikola");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[6]/div/input"));
        Grad2.sendKeys("Beograd");
        WebElement Ulica2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Ulica2.sendKeys("Trte Mrte 23");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[7]/div/input"));
        Fon2.sendKeys("0684555665");
        WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[3]/div/button[1]/span"));
        js.executeScript("arguments[0].click();", Azuriraj);
        Thread.sleep(8000);
        WebElement LICNO_PREUZIMANJE = driver.findElement(By.id("s_method_freeshipping_freeshipping"));
        wdWait.until(ExpectedConditions.elementToBeClickable(LICNO_PREUZIMANJE));
        LICNO_PREUZIMANJE.click();
        WebElement GOTOVINA = driver.findElement(By.id("cashondelivery"));
        wdWait.until(ExpectedConditions.elementToBeClickable(GOTOVINA));
        js.executeScript("arguments[0].click();", GOTOVINA);
        WebElement Saglasnost = driver.findElement(By.name("agreement[1]"));
        js.executeScript("arguments[0].click();", Saglasnost);
        Thread.sleep(5000);
        //WebElement Kupi = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[2]/div[2]/div[4]/div/div/button"));
        //Kupi.click();
    }

    public static void LicnoIPreracun() throws InterruptedException{
        String url = "https://miele.dev.smartweb.rs/";
        driver.navigate().to(url);
        driver.get("https://miele.dev.smartweb.rs/");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/div[1]/nav/ul[1]/li[3]/a/span[2]")));
        WebElement NegaVesa = driver.findElement(By.xpath("/html/body/div[5]/div[1]/nav/ul[1]/li[3]/a/span[2]"));
        NegaVesa.click();
        Select Sorter = new Select(driver.findElement(By.id("sorter")));
        Sorter.selectByVisibleText("Cena");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[3]/div[1]/div[5]/div[2]/ol/li[1]/div/a/span/span/img")));
        WebElement Kapsula = driver.findElement(By.xpath("/html/body/div[5]/main/div[3]/div[1]/div[5]/div[2]/ol/li[1]/div/a/span/span/img"));
        Kapsula.click();
        WebElement Dodaj = driver.findElement(By.id("product-addtocart-button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Dodaj));
        Dodaj.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[1]/div[2]/div/div/div/a")));
        WebElement MiniK = driver.findElement(By.xpath("/html/body/div[5]/main/div[1]/div[2]/div/div/div/a"));
        MiniK.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[3]/div/div[2]/div[1]/ul/li[1]/button")));
        WebElement NastaviP = driver.findElement(By.xpath("/html/body/div[5]/main/div[3]/div/div[2]/div[1]/ul/li[1]/button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(NastaviP));
        NastaviP.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement Mejl = driver.findElement(By.id("customer-email"));
        Mejl.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime1 = driver.findElement(By.name("firstname"));
        Ime1.sendKeys("Nikola");
        WebElement Prezime1 = driver.findElement(By.name("lastname"));
        Prezime1.sendKeys("Cebic");
        WebElement Postanski1 = driver.findElement(By.name("postcode"));
        Postanski1.sendKeys("11090");
        WebElement Grad1 = driver.findElement(By.name("city"));
        Grad1.sendKeys("Beograd");
        WebElement Ulica1 = driver.findElement(By.name("street[0]"));
        Ulica1.sendKeys("Blabla 23");
        WebElement Fon1 = driver.findElement(By.name("telephone"));
        Fon1.sendKeys("065789562");
        WebElement MojaAdresa = driver.findElement(By.name("billing-address-same-as-shipping"));
        js.executeScript("arguments[0].click();", MojaAdresa);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input")));
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        Ime2.sendKeys("Nikola");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[6]/div/input"));
        Grad2.sendKeys("Beograd");
        WebElement Ulica2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Ulica2.sendKeys("Trte Mrte 23");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[7]/div/input"));
        Fon2.sendKeys("0684555665");
        WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[3]/div/button[1]/span"));
        js.executeScript("arguments[0].click();", Azuriraj);
        Thread.sleep(8000);
        WebElement LICNO_PREUZIMANJE = driver.findElement(By.id("s_method_freeshipping_freeshipping"));
        wdWait.until(ExpectedConditions.elementToBeClickable(LICNO_PREUZIMANJE));
        LICNO_PREUZIMANJE.click();
        WebElement PRERACUN = driver.findElement(By.id("checkmo"));
        wdWait.until(ExpectedConditions.elementToBeClickable(PRERACUN));
        js.executeScript("arguments[0].click();", PRERACUN);
        WebElement Saglasnost = driver.findElement(By.name("agreement[1]"));
        js.executeScript("arguments[0].click();", Saglasnost);
        Thread.sleep(5000);
        //WebElement Kupi = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[2]/div[2]/div[4]/div/div/button"));
        //Kupi.click();
    }

    public static void LicnoIKupovinaNaRate() throws InterruptedException{
        String url = "https://miele.dev.smartweb.rs/";
        driver.navigate().to(url);
        driver.get("https://miele.dev.smartweb.rs/");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/div[1]/nav/ul[1]/li[3]/a/span[2]")));
        WebElement NegaVesa = driver.findElement(By.xpath("/html/body/div[5]/div[1]/nav/ul[1]/li[3]/a/span[2]"));
        NegaVesa.click();
        Select Sorter = new Select(driver.findElement(By.id("sorter")));
        Sorter.selectByVisibleText("Cena");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[3]/div[1]/div[5]/div[2]/ol/li[1]/div/a/span/span/img")));
        WebElement Kapsula = driver.findElement(By.xpath("/html/body/div[5]/main/div[3]/div[1]/div[5]/div[2]/ol/li[1]/div/a/span/span/img"));
        Kapsula.click();
        WebElement Dodaj = driver.findElement(By.id("product-addtocart-button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(Dodaj));
        Dodaj.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[1]/div[2]/div/div/div/a")));
        WebElement MiniK = driver.findElement(By.xpath("/html/body/div[5]/main/div[1]/div[2]/div/div/div/a"));
        MiniK.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[3]/div/div[2]/div[1]/ul/li[1]/button")));
        WebElement NastaviP = driver.findElement(By.xpath("/html/body/div[5]/main/div[3]/div/div[2]/div[1]/ul/li[1]/button"));
        wdWait.until(ExpectedConditions.elementToBeClickable(NastaviP));
        NastaviP.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.id("customer-email")));
        WebElement Mejl = driver.findElement(By.id("customer-email"));
        Mejl.sendKeys("nikola.cebic@smartweb.rs");
        WebElement Ime1 = driver.findElement(By.name("firstname"));
        Ime1.sendKeys("Nikola");
        WebElement Prezime1 = driver.findElement(By.name("lastname"));
        Prezime1.sendKeys("Cebic");
        WebElement Postanski1 = driver.findElement(By.name("postcode"));
        Postanski1.sendKeys("11090");
        WebElement Grad1 = driver.findElement(By.name("city"));
        Grad1.sendKeys("Beograd");
        WebElement Ulica1 = driver.findElement(By.name("street[0]"));
        Ulica1.sendKeys("Blabla 23");
        WebElement Fon1 = driver.findElement(By.name("telephone"));
        Fon1.sendKeys("065789562");
        WebElement MojaAdresa = driver.findElement(By.name("billing-address-same-as-shipping"));
        js.executeScript("arguments[0].click();", MojaAdresa);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input")));
        WebElement Ime2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[1]/div/input"));
        Ime2.sendKeys("Nikola");
        WebElement Prezime2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[2]/div/input"));
        Prezime2.sendKeys("Cebic");
        WebElement Postanski2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[5]/div/input"));
        Postanski2.sendKeys("11090");
        WebElement Grad2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[6]/div/input"));
        Grad2.sendKeys("Beograd");
        WebElement Ulica2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/fieldset/div/div/div/input"));
        Ulica2.sendKeys("Trte Mrte 23");
        WebElement Fon2 = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[2]/div/form/fieldset/div[7]/div/input"));
        Fon2.sendKeys("0684555665");
        WebElement Azuriraj = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[1]/div[1]/li/div/div/div/fieldset/div[3]/div/button[1]/span"));
        js.executeScript("arguments[0].click();", Azuriraj);
        Thread.sleep(8000);
        WebElement LICNO_PREUZIMANJE = driver.findElement(By.id("s_method_freeshipping_freeshipping"));
        wdWait.until(ExpectedConditions.elementToBeClickable(LICNO_PREUZIMANJE));
        LICNO_PREUZIMANJE.click();
        WebElement KUPOVINANARATE = driver.findElement(By.id("banktransfer"));
        wdWait.until(ExpectedConditions.elementToBeClickable(KUPOVINANARATE));
        js.executeScript("arguments[0].click();", KUPOVINANARATE);
        WebElement Saglasnost = driver.findElement(By.name("agreement[1]"));
        js.executeScript("arguments[0].click();", Saglasnost);
        Thread.sleep(5000);
        //WebElement Kupi = driver.findElement(By.xpath("/html/body/div[5]/main/div/div/div/div[5]/div[2]/div[2]/div[4]/div/div/button"));
        //Kupi.click();
    }

    public static void SearchH() throws InterruptedException{
        String url = "https://miele.dev.smartweb.rs/";
        driver.navigate().to(url);
        driver.get("https://miele.dev.smartweb.rs/");
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/header/div/div/div[1]/div[2]/button")));
        WebElement Lupa = driver.findElement(By.xpath("/html/body/div[5]/header/div/div/div[1]/div[2]/button"));
        Lupa.click();
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.name("q")));
        WebElement Kucanje = driver.findElement(By.name("q"));
        Kucanje.click();
        Kucanje.sendKeys("masine");
        Kucanje.sendKeys(Keys.ENTER);
        wdWait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[5]/main/div[2]/div[1]/div[5]/div/div[2]/ol")));
        WebElement Result = driver.findElement(By.xpath("/html/body/div[5]/main/div[2]/div[1]/div[5]/div/div[2]/ol"));
        System.out.println(Result.getText());
    }
}
